/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 BoengPlane.gltf 
Author: hikami3150 (https://sketchfab.com/hikami3150)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/boeing-777-300er-model-322e7961d2024bba834887878d2d49a2
Title: Boeing 777-300ER Model
*/

import  {  useEffect } from "react"
import { useGLTF } from "@react-three/drei"

// Preload the GLTF model at the Top
useGLTF.preload("/BoengPlane.gltf")

export default function BoengPlane({ onLoad, ...props }:any) {
  const { nodes, materials } = useGLTF<any>("/BoengPlane.gltf")

  // Call onLoad when the model is ready
  useEffect(() => {
    if (nodes && materials && onLoad) {
      onLoad();
    }
  }, [nodes, materials, onLoad]);

  return (
    <group  {...props} dispose={null}>
      <group scale={0.012}>
        <group
          position={[-10.121, 27.695, 3.415]}
          scale={[53.882, 2.414, 53.882]}
        >
          <mesh
            geometry={nodes.wing_Material058_0.geometry}
            material={materials["Material.058"]}
          />
          <mesh
            geometry={nodes.wing_Material065_0.geometry}
            material={materials["Material.065"]}
          />
          <mesh
            geometry={nodes.wing_Material083_0.geometry}
            material={materials["Material.083"]}
          />
        </group>
        <group
          position={[-226.142, 14.006, 3.829]}
          rotation={[-Math.PI / 2, Math.PI / 2, 0]}
          scale={[0.203, 0.203, 0.137]}
        >
          <mesh
            geometry={nodes.Cylinder097_Material075_0.geometry}
            material={materials["Material.075"]}
          />
          <mesh
            geometry={nodes.Cylinder097_Material076_0.geometry}
            material={materials["Material.076"]}
          />
        </group>
        <group
          position={[-240.869, 31.735, 11.54]}
          rotation={[-Math.PI / 2, Math.PI / 2, 0]}
          scale={24.392}
        >
          <mesh
            geometry={nodes.Cylinder094_Material002_0.geometry}
            material={materials["Material.002"]}
          />
          <mesh
            geometry={nodes.Cylinder094_Material001_0.geometry}
            material={materials["Material.001"]}
          />
          <mesh
            geometry={nodes.Cylinder094_Material001_0_1.geometry}
            material={materials["Material.001"]}
          />
          <mesh
            geometry={nodes.Cylinder094_Material027_0.geometry}
            material={materials["Material.027"]}
          />
          <mesh
            geometry={nodes.Cylinder094_Material028_0.geometry}
            material={materials["Material.028"]}
          />
          <mesh
            geometry={nodes.Cylinder094_Material004_0.geometry}
            material={materials["Material.004"]}
          />
          <mesh
            geometry={nodes.Cylinder094_Material020_0.geometry}
            material={materials["Material.020"]}
          />
          <mesh
            geometry={nodes.Cylinder094_Material021_0.geometry}
            material={materials["Material.021"]}
          />
          <mesh
            geometry={nodes.Cylinder094_Material026_0.geometry}
            material={materials["Material.026"]}
          />
        </group>
        <group
          position={[-227.239, 8.959, 4.585]}
          rotation={[Math.PI / 2, 0, Math.PI / 9]}
          scale={[-0.311, 0.311, 0.311]}
        >
          <mesh
            geometry={nodes.Cylinder090_Material067_0.geometry}
            material={materials["Material.067"]}
          />
          <mesh
            geometry={nodes.Cylinder090_Material070_0.geometry}
            material={materials["Material.070"]}
          />
        </group>
        <group
          position={[-227.239, 8.959, 7.487]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={[-0.311, 0.311, 0.311]}
        >
          <mesh
            geometry={nodes.Cylinder089_Material067_0.geometry}
            material={materials["Material.067"]}
          />
          <mesh
            geometry={nodes.Cylinder089_Material070_0.geometry}
            material={materials["Material.070"]}
          />
        </group>
        <group
          position={[-225.293, 1.506, 2.855]}
          rotation={[Math.PI, 0, Math.PI]}
          scale={[4.284, 4.284, 1.746]}
        >
          <mesh
            geometry={nodes.Cylinder086_Material057_0.geometry}
            material={materials["Material.057"]}
          />
          <mesh
            geometry={nodes.Cylinder086_Material024_0.geometry}
            material={materials["Material.024"]}
          />
          <mesh
            geometry={nodes.Cylinder086_Material059_0.geometry}
            material={materials["Material.059"]}
          />
          <mesh
            geometry={nodes.Cylinder086_Material066_0.geometry}
            material={materials["Material.066"]}
          />
        </group>
        <group
          position={[8.482, 19.37, -40.113]}
          rotation={[0, 1.313, 0]}
          scale={0.215}
        >
          <mesh
            geometry={nodes.Cylinder083_Material061_0.geometry}
            material={materials["Material.061"]}
          />
          <mesh
            geometry={nodes.Cylinder083_Material060_0.geometry}
            material={materials["Material.060"]}
          />
        </group>
        <group
          position={[-225.293, 1.506, 8.935]}
          scale={[4.284, 4.284, 1.746]}
        >
          <mesh
            geometry={nodes.Cylinder082_Material057_0.geometry}
            material={materials["Material.057"]}
          />
          <mesh
            geometry={nodes.Cylinder082_Material024_0.geometry}
            material={materials["Material.024"]}
          />
          <mesh
            geometry={nodes.Cylinder082_Material059_0.geometry}
            material={materials["Material.059"]}
          />
          <mesh
            geometry={nodes.Cylinder082_Material066_0.geometry}
            material={materials["Material.066"]}
          />
        </group>
        <group
          position={[12.347, 16.177, -35.431]}
          rotation={[2.583, -1.265, 2.561]}
          scale={0.215}
        >
          <mesh
            geometry={nodes.Cylinder081_Material060_0.geometry}
            material={materials["Material.060"]}
          />
          <mesh
            geometry={nodes.Cylinder081_Material048_0.geometry}
            material={materials["Material.048"]}
          />
          <mesh
            geometry={nodes.Cylinder081_Material049_0.geometry}
            material={materials["Material.049"]}
          />
          <mesh
            geometry={nodes.Cylinder081_Material045_0.geometry}
            material={materials["Material.045"]}
          />
          <mesh
            geometry={nodes.Cylinder081_Material050_0.geometry}
            material={materials["Material.050"]}
          />
          <mesh
            geometry={nodes.Cylinder081_Material051_0.geometry}
            material={materials["Material.051"]}
          />
          <mesh
            geometry={nodes.Cylinder081_Material052_0.geometry}
            material={materials["Material.052"]}
          />
        </group>
        <group
          position={[13.542, 18.134, -39.598]}
          rotation={[0, 1.313, 0]}
          scale={0.215}
        >
          <mesh
            geometry={nodes.Cylinder080_Material037_0.geometry}
            material={materials["Material.037"]}
          />
          <mesh
            geometry={nodes.Cylinder080_Material038_0.geometry}
            material={materials["Material.038"]}
          />
          <mesh
            geometry={nodes.Cylinder080_Material051_0.geometry}
            material={materials["Material.051"]}
          />
        </group>
        <group
          position={[0.743, 2.823, -36.791]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[-1.137, 0.751, 0.134]}
        >
          <mesh
            geometry={nodes.Cylinder079_Material056_0.geometry}
            material={materials["Material.056"]}
          />
          <mesh
            geometry={nodes.Cylinder079_Material034_0.geometry}
            material={materials["Material.034"]}
          />
          <mesh
            geometry={nodes.Cylinder079_Material044_0.geometry}
            material={materials["Material.044"]}
          />
        </group>
        <group
          position={[23.83, 3.223, -43.167]}
          rotation={[Math.PI, 0, 0]}
          scale={0.179}
        >
          <mesh
            geometry={nodes.Cylinder077_Material042_0.geometry}
            material={materials["Material.042"]}
          />
          <mesh
            geometry={nodes.Cylinder077_Material032_0.geometry}
            material={materials["Material.032"]}
          />
          <mesh
            geometry={nodes.Cylinder077_Material029_0.geometry}
            material={materials["Material.029"]}
          />
          <mesh
            geometry={nodes.Cylinder077_Material030_0.geometry}
            material={materials["Material.030"]}
          />
          <mesh
            geometry={nodes.Cylinder077_Material033_0.geometry}
            material={materials["Material.033"]}
          />
          <mesh
            geometry={nodes.Cylinder077_Material031_0.geometry}
            material={materials["Material.031"]}
          />
        </group>
        <group
          position={[11.196, 3.223, -43.167]}
          rotation={[Math.PI, 0, 0]}
          scale={0.179}
        >
          <mesh
            geometry={nodes.Cylinder076_Material042_0.geometry}
            material={materials["Material.042"]}
          />
          <mesh
            geometry={nodes.Cylinder076_Material032_0.geometry}
            material={materials["Material.032"]}
          />
          <mesh
            geometry={nodes.Cylinder076_Material029_0.geometry}
            material={materials["Material.029"]}
          />
          <mesh
            geometry={nodes.Cylinder076_Material030_0.geometry}
            material={materials["Material.030"]}
          />
          <mesh
            geometry={nodes.Cylinder076_Material033_0.geometry}
            material={materials["Material.033"]}
          />
          <mesh
            geometry={nodes.Cylinder076_Material031_0.geometry}
            material={materials["Material.031"]}
          />
        </group>
        <group
          position={[-1.296, 3.223, -43.167]}
          rotation={[Math.PI, 0, 0]}
          scale={0.179}
        >
          <mesh
            geometry={nodes.Cylinder075_Material042_0.geometry}
            material={materials["Material.042"]}
          />
          <mesh
            geometry={nodes.Cylinder075_Material032_0.geometry}
            material={materials["Material.032"]}
          />
          <mesh
            geometry={nodes.Cylinder075_Material029_0.geometry}
            material={materials["Material.029"]}
          />
          <mesh
            geometry={nodes.Cylinder075_Material030_0.geometry}
            material={materials["Material.030"]}
          />
          <mesh
            geometry={nodes.Cylinder075_Material033_0.geometry}
            material={materials["Material.033"]}
          />
          <mesh
            geometry={nodes.Cylinder075_Material031_0.geometry}
            material={materials["Material.031"]}
          />
        </group>
        <group position={[23.83, 3.179, -30.342]} scale={0.179}>
          <mesh
            geometry={nodes.Cylinder073_Material042_0.geometry}
            material={materials["Material.042"]}
          />
          <mesh
            geometry={nodes.Cylinder073_Material032_0.geometry}
            material={materials["Material.032"]}
          />
          <mesh
            geometry={nodes.Cylinder073_Material029_0.geometry}
            material={materials["Material.029"]}
          />
          <mesh
            geometry={nodes.Cylinder073_Material030_0.geometry}
            material={materials["Material.030"]}
          />
          <mesh
            geometry={nodes.Cylinder073_Material033_0.geometry}
            material={materials["Material.033"]}
          />
          <mesh
            geometry={nodes.Cylinder073_Material031_0.geometry}
            material={materials["Material.031"]}
          />
        </group>
        <group
          position={[13.542, 18.134, 46.088]}
          rotation={[0, 1.313, 0]}
          scale={0.215}
        >
          <mesh
            geometry={nodes.Cylinder072_Material045_0.geometry}
            material={materials["Material.045"]}
          />
          <mesh
            geometry={nodes.Cylinder072_Material050_0.geometry}
            material={materials["Material.050"]}
          />
          <mesh
            geometry={nodes.Cylinder072_Material037_0.geometry}
            material={materials["Material.037"]}
          />
          <mesh
            geometry={nodes.Cylinder072_Material038_0.geometry}
            material={materials["Material.038"]}
          />
          <mesh
            geometry={nodes.Cylinder072_Material060_0.geometry}
            material={materials["Material.060"]}
          />
          <mesh
            geometry={nodes.Cylinder072_Material051_0.geometry}
            material={materials["Material.051"]}
          />
          <mesh
            geometry={nodes.Cylinder072_Material052_0.geometry}
            material={materials["Material.052"]}
          />
        </group>
        <group position={[11.196, 3.179, -30.342]} scale={0.179}>
          <mesh
            geometry={nodes.Cylinder070_Material042_0.geometry}
            material={materials["Material.042"]}
          />
          <mesh
            geometry={nodes.Cylinder070_Material032_0.geometry}
            material={materials["Material.032"]}
          />
          <mesh
            geometry={nodes.Cylinder070_Material029_0.geometry}
            material={materials["Material.029"]}
          />
          <mesh
            geometry={nodes.Cylinder070_Material030_0.geometry}
            material={materials["Material.030"]}
          />
          <mesh
            geometry={nodes.Cylinder070_Material033_0.geometry}
            material={materials["Material.033"]}
          />
          <mesh
            geometry={nodes.Cylinder070_Material031_0.geometry}
            material={materials["Material.031"]}
          />
        </group>
        <group position={[-1.296, 3.179, -30.342]} scale={0.179}>
          <mesh
            geometry={nodes.Cylinder067_Material042_0.geometry}
            material={materials["Material.042"]}
          />
          <mesh
            geometry={nodes.Cylinder067_Material032_0.geometry}
            material={materials["Material.032"]}
          />
          <mesh
            geometry={nodes.Cylinder067_Material029_0.geometry}
            material={materials["Material.029"]}
          />
          <mesh
            geometry={nodes.Cylinder067_Material030_0.geometry}
            material={materials["Material.030"]}
          />
          <mesh
            geometry={nodes.Cylinder067_Material033_0.geometry}
            material={materials["Material.033"]}
          />
          <mesh
            geometry={nodes.Cylinder067_Material031_0.geometry}
            material={materials["Material.031"]}
          />
        </group>
        <group
          position={[0.744, 2.823, 48.894]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[-1.137, 0.751, 0.134]}
        >
          <mesh
            geometry={nodes.Cylinder065_Material056_0.geometry}
            material={materials["Material.056"]}
          />
          <mesh
            geometry={nodes.Cylinder065_Material034_0.geometry}
            material={materials["Material.034"]}
          />
          <mesh
            geometry={nodes.Cylinder065_Material044_0.geometry}
            material={materials["Material.044"]}
          />
        </group>
        <group
          position={[23.83, 3.223, 42.519]}
          rotation={[Math.PI, 0, 0]}
          scale={0.179}
        >
          <mesh
            geometry={nodes.Cylinder061_Material042_0.geometry}
            material={materials["Material.042"]}
          />
          <mesh
            geometry={nodes.Cylinder061_Material032_0.geometry}
            material={materials["Material.032"]}
          />
          <mesh
            geometry={nodes.Cylinder061_Material029_0.geometry}
            material={materials["Material.029"]}
          />
          <mesh
            geometry={nodes.Cylinder061_Material030_0.geometry}
            material={materials["Material.030"]}
          />
          <mesh
            geometry={nodes.Cylinder061_Material033_0.geometry}
            material={materials["Material.033"]}
          />
          <mesh
            geometry={nodes.Cylinder061_Material031_0.geometry}
            material={materials["Material.031"]}
          />
        </group>
        <group
          position={[14.505, 3.375, -36.791]}
          rotation={[Math.PI / 2, -Math.PI / 2, 0]}
          scale={[-1.12, 1.12, 12.138]}
        >
          <mesh
            geometry={nodes.Cylinder059_Material035_0.geometry}
            material={materials["Material.035"]}
          />
          <mesh
            geometry={nodes.Cylinder059_Material036_0.geometry}
            material={materials["Material.036"]}
          />
        </group>
        <group
          position={[14.505, 3.375, 48.894]}
          rotation={[Math.PI / 2, -Math.PI / 2, 0]}
          scale={[-1.12, 1.12, 12.138]}
        >
          <mesh
            geometry={nodes.Cylinder055_Material035_0.geometry}
            material={materials["Material.035"]}
          />
          <mesh
            geometry={nodes.Cylinder055_Material036_0.geometry}
            material={materials["Material.036"]}
          />
        </group>
        <group position={[27.166, 3.275, 48.894]} scale={[1.493, 1.493, 3.522]}>
          <mesh
            geometry={nodes.Cylinder054_Material034_0.geometry}
            material={materials["Material.034"]}
          />
          <mesh
            geometry={nodes.Cylinder054_Material056_0.geometry}
            material={materials["Material.056"]}
          />
          <mesh
            geometry={nodes.Cylinder054_Material040_0.geometry}
            material={materials["Material.040"]}
          />
          <mesh
            geometry={nodes.Cylinder054_Material062_0.geometry}
            material={materials["Material.062"]}
          />
          <mesh
            geometry={nodes.Cylinder054_Material047_0.geometry}
            material={materials["Material.047"]}
          />
          <mesh
            geometry={nodes.Cylinder054_Material063_0.geometry}
            material={materials["Material.063"]}
          />
        </group>
        <group
          position={[27.166, 3.275, -36.791]}
          scale={[1.493, 1.493, 3.522]}
        >
          <mesh
            geometry={nodes.Cylinder052_Material034_0.geometry}
            material={materials["Material.034"]}
          />
          <mesh
            geometry={nodes.Cylinder052_Material056_0.geometry}
            material={materials["Material.056"]}
          />
          <mesh
            geometry={nodes.Cylinder052_Material040_0.geometry}
            material={materials["Material.040"]}
          />
          <mesh
            geometry={nodes.Cylinder052_Material062_0.geometry}
            material={materials["Material.062"]}
          />
          <mesh
            geometry={nodes.Cylinder052_Material047_0.geometry}
            material={materials["Material.047"]}
          />
          <mesh
            geometry={nodes.Cylinder052_Material063_0.geometry}
            material={materials["Material.063"]}
          />
        </group>
        <group
          position={[11.197, 3.223, 42.519]}
          rotation={[Math.PI, 0, 0]}
          scale={0.179}
        >
          <mesh
            geometry={nodes.Cylinder050_Material042_0.geometry}
            material={materials["Material.042"]}
          />
          <mesh
            geometry={nodes.Cylinder050_Material032_0.geometry}
            material={materials["Material.032"]}
          />
          <mesh
            geometry={nodes.Cylinder050_Material029_0.geometry}
            material={materials["Material.029"]}
          />
          <mesh
            geometry={nodes.Cylinder050_Material030_0.geometry}
            material={materials["Material.030"]}
          />
          <mesh
            geometry={nodes.Cylinder050_Material033_0.geometry}
            material={materials["Material.033"]}
          />
          <mesh
            geometry={nodes.Cylinder050_Material031_0.geometry}
            material={materials["Material.031"]}
          />
        </group>
        <group
          position={[-1.296, 3.223, 42.519]}
          rotation={[Math.PI, 0, 0]}
          scale={0.179}
        >
          <mesh
            geometry={nodes.Cylinder049_Material042_0.geometry}
            material={materials["Material.042"]}
          />
          <mesh
            geometry={nodes.Cylinder049_Material032_0.geometry}
            material={materials["Material.032"]}
          />
          <mesh
            geometry={nodes.Cylinder049_Material029_0.geometry}
            material={materials["Material.029"]}
          />
          <mesh
            geometry={nodes.Cylinder049_Material030_0.geometry}
            material={materials["Material.030"]}
          />
          <mesh
            geometry={nodes.Cylinder049_Material033_0.geometry}
            material={materials["Material.033"]}
          />
          <mesh
            geometry={nodes.Cylinder049_Material031_0.geometry}
            material={materials["Material.031"]}
          />
        </group>
        <group position={[23.83, 3.179, 55.343]} scale={0.179}>
          <mesh
            geometry={nodes.Cylinder048_Material042_0.geometry}
            material={materials["Material.042"]}
          />
          <mesh
            geometry={nodes.Cylinder048_Material032_0.geometry}
            material={materials["Material.032"]}
          />
          <mesh
            geometry={nodes.Cylinder048_Material029_0.geometry}
            material={materials["Material.029"]}
          />
          <mesh
            geometry={nodes.Cylinder048_Material030_0.geometry}
            material={materials["Material.030"]}
          />
          <mesh
            geometry={nodes.Cylinder048_Material033_0.geometry}
            material={materials["Material.033"]}
          />
          <mesh
            geometry={nodes.Cylinder048_Material031_0.geometry}
            material={materials["Material.031"]}
          />
        </group>
        <group position={[11.197, 3.179, 55.343]} scale={0.179}>
          <mesh
            geometry={nodes.Cylinder047_Material042_0.geometry}
            material={materials["Material.042"]}
          />
          <mesh
            geometry={nodes.Cylinder047_Material032_0.geometry}
            material={materials["Material.032"]}
          />
          <mesh
            geometry={nodes.Cylinder047_Material029_0.geometry}
            material={materials["Material.029"]}
          />
          <mesh
            geometry={nodes.Cylinder047_Material030_0.geometry}
            material={materials["Material.030"]}
          />
          <mesh
            geometry={nodes.Cylinder047_Material033_0.geometry}
            material={materials["Material.033"]}
          />
          <mesh
            geometry={nodes.Cylinder047_Material031_0.geometry}
            material={materials["Material.031"]}
          />
        </group>
        <group position={[-1.296, 3.179, 55.343]} scale={0.179}>
          <mesh
            geometry={nodes.Cylinder046_Material042_0.geometry}
            material={materials["Material.042"]}
          />
          <mesh
            geometry={nodes.Cylinder046_Material032_0.geometry}
            material={materials["Material.032"]}
          />
          <mesh
            geometry={nodes.Cylinder046_Material029_0.geometry}
            material={materials["Material.029"]}
          />
          <mesh
            geometry={nodes.Cylinder046_Material030_0.geometry}
            material={materials["Material.030"]}
          />
          <mesh
            geometry={nodes.Cylinder046_Material033_0.geometry}
            material={materials["Material.033"]}
          />
          <mesh
            geometry={nodes.Cylinder046_Material031_0.geometry}
            material={materials["Material.031"]}
          />
        </group>
        <group
          position={[-173.983, 67.75, 5.882]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[1.527, 1.527, 0.274]}
        >
          <mesh
            geometry={nodes.Cylinder045_Material016_0.geometry}
            material={materials["Material.016"]}
          />
          <mesh
            geometry={nodes.Cylinder045_Material023_0.geometry}
            material={materials["Material.023"]}
          />
        </group>
        <group
          position={[-112.14, 43.408, 5.883]}
          rotation={[-Math.PI / 2, Math.PI / 2, 0]}
          scale={24.392}
        >
          <mesh
            geometry={nodes.Cylinder039_Material001_0.geometry}
            material={materials["Material.001"]}
          />
          <mesh
            geometry={nodes.Cylinder039_Material002_0.geometry}
            material={materials["Material.002"]}
          />
        </group>
        <group
          position={[-112.14, 43.408, 5.883]}
          rotation={[-Math.PI / 2, Math.PI / 2, 0]}
          scale={24.392}
        >
          <mesh
            geometry={nodes.Cylinder038_Material001_0.geometry}
            material={materials["Material.001"]}
          />
          <mesh
            geometry={nodes.Cylinder038_Material002_0.geometry}
            material={materials["Material.002"]}
          />
        </group>
        <group
          position={[-54.326, 22.567, -70.356]}
          rotation={[-1.571, 0, 0]}
          scale={[-0.134, 0.818, 0.818]}
        >
          <mesh
            geometry={nodes.Cylinder029_Material005_0.geometry}
            material={materials["Material.005"]}
          />
          <mesh
            geometry={nodes.Cylinder029_Material006_0.geometry}
            material={materials["Material.006"]}
          />
        </group>
        <group
          position={[-50.906, 22.567, -70.331]}
          rotation={[-Math.PI / 2, Math.PI / 2, 0]}
          scale={16.612}
        >
          <mesh
            geometry={nodes.Cylinder027_Material008_0.geometry}
            material={materials["Material.008"]}
          />
          <mesh
            geometry={nodes.Cylinder027_Material011_0.geometry}
            material={materials["Material.011"]}
          />
          <mesh
            geometry={nodes.Cylinder027_Material009_0.geometry}
            material={materials["Material.009"]}
          />
          <mesh
            geometry={nodes.Cylinder027_Material010_0.geometry}
            material={materials["Material.010"]}
          />
          <mesh
            geometry={nodes.Cylinder027_Material012_0.geometry}
            material={materials["Material.012"]}
          />
          <mesh
            geometry={nodes.Cylinder027_Material013_0.geometry}
            material={materials["Material.013"]}
          />
          <mesh
            geometry={nodes.Cylinder027_Material014_0.geometry}
            material={materials["Material.014"]}
          />
        </group>
        <group
          position={[-54.326, 22.438, 82.15]}
          rotation={[-1.571, 0, 0]}
          scale={[-0.134, 0.818, 0.818]}
        >
          <mesh
            geometry={nodes.Cylinder026_Material005_0.geometry}
            material={materials["Material.005"]}
          />
          <mesh
            geometry={nodes.Cylinder026_Material006_0.geometry}
            material={materials["Material.006"]}
          />
        </group>
        <group
          position={[-50.906, 22.438, 82.176]}
          rotation={[-Math.PI / 2, Math.PI / 2, 0]}
          scale={16.612}
        >
          <mesh
            geometry={nodes.Cylinder024_Material008_0.geometry}
            material={materials["Material.008"]}
          />
          <mesh
            geometry={nodes.Cylinder024_Material011_0.geometry}
            material={materials["Material.011"]}
          />
          <mesh
            geometry={nodes.Cylinder024_Material009_0.geometry}
            material={materials["Material.009"]}
          />
          <mesh
            geometry={nodes.Cylinder024_Material010_0.geometry}
            material={materials["Material.010"]}
          />
          <mesh
            geometry={nodes.Cylinder024_Material012_0.geometry}
            material={materials["Material.012"]}
          />
          <mesh
            geometry={nodes.Cylinder024_Material013_0.geometry}
            material={materials["Material.013"]}
          />
          <mesh
            geometry={nodes.Cylinder024_Material014_0.geometry}
            material={materials["Material.014"]}
          />
        </group>
        <group
          position={[13.542, 18.134, 46.088]}
          rotation={[0, 1.313, 0]}
          scale={0.215}
        >
          <mesh
            geometry={nodes.Cylinder009_Material061_0.geometry}
            material={materials["Material.061"]}
          />
          <mesh
            geometry={nodes.Cylinder009_Material060_0.geometry}
            material={materials["Material.060"]}
          />
        </group>
        <group
          position={[-224.509, 3.904, 6.779]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[0.357, 0.18, 0.357]}
        >
          <mesh
            geometry={nodes.Cube042_Material072_0.geometry}
            material={materials["Material.072"]}
          />
          <mesh
            geometry={nodes.Cube042_Material073_0.geometry}
            material={materials["Material.073"]}
          />
        </group>
        <group
          position={[-12.346, 33.992, -69.105]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[9.411, 3.137, 10.02]}
        >
          <mesh
            geometry={nodes.Cube008__0.geometry}
            material={materials["Cylinder.091__0"]}
          />
          <mesh
            geometry={nodes.Cube008__0_1.geometry}
            material={materials["Cylinder.091__0"]}
          />
          <mesh
            geometry={nodes.Cube008__0_2.geometry}
            material={materials["Cylinder.091__0"]}
          />
          <mesh
            geometry={nodes.Cube008__0_3.geometry}
            material={materials["Cylinder.091__0"]}
          />
          <mesh
            geometry={nodes.Cube008__0_4.geometry}
            material={materials["Cylinder.091__0"]}
          />
          <mesh
            geometry={nodes.Cube008__0_5.geometry}
            material={materials["Cylinder.091__0"]}
          />
          <mesh
            geometry={nodes.Cube008__0_6.geometry}
            material={materials["Cylinder.091__0"]}
          />
        </group>
        <group
          position={[-12.346, 33.992, 80.864]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[9.411, 3.137, 10.02]}
        >
          <mesh
            geometry={nodes.Cube006__0.geometry}
            material={materials["Cylinder.091__0"]}
          />
          <mesh
            geometry={nodes.Cube006__0_1.geometry}
            material={materials["Cylinder.091__0"]}
          />
          <mesh
            geometry={nodes.Cube006__0_2.geometry}
            material={materials["Cylinder.091__0"]}
          />
          <mesh
            geometry={nodes.Cube006__0_3.geometry}
            material={materials["Cylinder.091__0"]}
          />
          <mesh
            geometry={nodes.Cube006__0_4.geometry}
            material={materials["Cylinder.091__0"]}
          />
          <mesh
            geometry={nodes.Cube006__0_5.geometry}
            material={materials["Cylinder.091__0"]}
          />
          <mesh
            geometry={nodes.Cube006__0_6.geometry}
            material={materials["Cylinder.091__0"]}
          />
        </group>
        <group
          position={[-240.869, 31.735, 11.54]}
          rotation={[-Math.PI / 2, Math.PI / 2, 0]}
          scale={24.392}
        >
          <mesh
            geometry={nodes.Cylinder001_Material002_0.geometry}
            material={materials["Material.002"]}
          />
          <mesh
            geometry={nodes.Cylinder001_Material001_0.geometry}
            material={materials["Material.001"]}
          />
          <mesh
            geometry={nodes.Cylinder001_Material020_0.geometry}
            material={materials["Material.020"]}
          />
          <mesh
            geometry={nodes.Cylinder001_Material004_0.geometry}
            material={materials["Material.004"]}
          />
          <mesh
            geometry={nodes.Cylinder001_Material021_0.geometry}
            material={materials["Material.021"]}
          />
          <mesh
            geometry={nodes.Cylinder001_Material026_0.geometry}
            material={materials["Material.026"]}
          />
          <mesh
            geometry={nodes.Cylinder001_Material028_0.geometry}
            material={materials["Material.028"]}
          />
        </group>
        <mesh
          geometry={nodes.NurbsPath028_Material080_0.geometry}
          material={materials["Material.080"]}
          position={[-224.564, 6.509, 7.018]}
          rotation={[-Math.PI / 2, Math.PI / 2, 0]}
          scale={2.722}
        />
        <mesh
          geometry={nodes.NurbsPath027_Material043_0.geometry}
          material={materials["Material.043"]}
          position={[-227.027, 1.103, 0.811]}
          rotation={[-Math.PI / 2, 0, -Math.PI]}
          scale={0.556}
        />
        <mesh
          geometry={nodes.NurbsPath026_Material043_0.geometry}
          material={materials["Material.043"]}
          position={[-223.559, 1.103, 10.979]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={0.556}
        />
        <mesh
          geometry={nodes.NurbsPath025_Material055_0.geometry}
          material={materials["Material.055"]}
          position={[11.013, 5.956, -38.137]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={1.2}
        />
        <mesh
          geometry={nodes.NurbsPath024_Material055_0.geometry}
          material={materials["Material.055"]}
          position={[11.013, 5.956, -34.828]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={1.2}
        />
        <mesh
          geometry={nodes.NurbsPath023_Material054_0.geometry}
          material={materials["Material.054"]}
          position={[9.565, 10.575, -37.026]}
          rotation={[-Math.PI / 2, 0, -Math.PI]}
          scale={5.039}
        />
        <mesh
          geometry={nodes.NurbsPath022_Material053_0.geometry}
          material={materials["Material.053"]}
          position={[3.309, 11.582, -37.334]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={[-3.584, 3.584, 3.584]}
        />
        <mesh
          geometry={nodes.NurbsPath021_Material043_0.geometry}
          material={materials["Material.043"]}
          position={[25.627, 3.179, -44.107]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.556}
        />
        <mesh
          geometry={nodes.NurbsPath020_Material043_0.geometry}
          material={materials["Material.043"]}
          position={[12.994, 3.179, -44.107]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.556}
        />
        <mesh
          geometry={nodes.NurbsPath019_Material043_0.geometry}
          material={materials["Material.043"]}
          position={[0.502, 3.179, -44.107]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.556}
        />
        <mesh
          geometry={nodes.NurbsPath018_Material043_0.geometry}
          material={materials["Material.043"]}
          position={[25.627, 3.223, -29.402]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={0.556}
        />
        <mesh
          geometry={nodes.NurbsPath017_Material054_0.geometry}
          material={materials["Material.054"]}
          position={[1.298, 15.384, 46.438]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={5.039}
        />
        <mesh
          geometry={nodes.NurbsPath016_Material043_0.geometry}
          material={materials["Material.043"]}
          position={[12.994, 3.223, -29.402]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={0.556}
        />
        <mesh
          geometry={nodes.NurbsPath015_Material043_0.geometry}
          material={materials["Material.043"]}
          position={[0.502, 3.223, -29.402]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={0.556}
        />
        <mesh
          geometry={nodes.NurbsPath014_Material053_0.geometry}
          material={materials["Material.053"]}
          position={[3.309, 11.582, 48.351]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={[-3.584, 3.584, 3.584]}
        />
        <mesh
          geometry={nodes.NurbsPath013_Material055_0.geometry}
          material={materials["Material.055"]}
          position={[11.013, 5.956, 47.549]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={1.2}
        />
        <mesh
          geometry={nodes.NurbsPath012_Material055_0.geometry}
          material={materials["Material.055"]}
          position={[11.013, 5.956, 50.857]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={1.2}
        />
        <mesh
          geometry={nodes.NurbsPath011_Material043_0.geometry}
          material={materials["Material.043"]}
          position={[25.627, 3.179, 41.579]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.556}
        />
        <mesh
          geometry={nodes.NurbsPath010_Material043_0.geometry}
          material={materials["Material.043"]}
          position={[12.994, 3.179, 41.579]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.556}
        />
        <mesh
          geometry={nodes.NurbsPath009_Material043_0.geometry}
          material={materials["Material.043"]}
          position={[0.502, 3.179, 41.579]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.556}
        />
        <mesh
          geometry={nodes.NurbsPath008_Material043_0.geometry}
          material={materials["Material.043"]}
          position={[25.627, 3.223, 56.283]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={0.556}
        />
        <mesh
          geometry={nodes.NurbsPath007_Material043_0.geometry}
          material={materials["Material.043"]}
          position={[12.994, 3.223, 56.283]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={0.556}
        />
        <mesh
          geometry={nodes.NurbsPath006_Material043_0.geometry}
          material={materials["Material.043"]}
          position={[0.502, 3.223, 56.283]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={0.556}
        />
        <mesh
          geometry={nodes.NurbsPath005_Material025_0.geometry}
          material={materials["Material.025"]}
          position={[-249.499, 32.218, -8.421]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={[0.751, 1.071, 1.071]}
        />
        <mesh
          geometry={nodes.NurbsPath004_Material025_0.geometry}
          material={materials["Material.025"]}
          position={[-249.482, 28.823, -5.507]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={[0.751, 1.071, 1.071]}
        />
        <mesh
          geometry={nodes.NurbsPath003_Material025_0.geometry}
          material={materials["Material.025"]}
          position={[-251.136, 28.823, 15.974]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[0.751, 1.071, 1.071]}
        />
        <mesh
          geometry={nodes.NurbsPath002_Material025_0.geometry}
          material={materials["Material.025"]}
          position={[-247.845, 32.218, 21.434]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[0.751, 1.071, 1.071]}
        />
        <mesh
          geometry={nodes.Cylinder102_Material001_0.geometry}
          material={materials["Material.001"]}
          position={[-228.621, 19.689, -0.482]}
          rotation={[0.906, 1.299, -0.934]}
          scale={24.392}
        />
        <mesh
          geometry={nodes.Cylinder100_Material001_0.geometry}
          material={materials["Material.001"]}
          position={[-228.541, 19.555, 11.993]}
          rotation={[2.094, 1.335, 1.128]}
          scale={24.392}
        />
        <mesh
          geometry={nodes.Cylinder099_Material077_0.geometry}
          material={materials["Material.077"]}
          position={[-229.56, 15.58, 5.963]}
          scale={[0.427, 0.427, 0.599]}
        />
        <mesh
          geometry={nodes.Cylinder098_Material077_0.geometry}
          material={materials["Material.077"]}
          position={[-226.453, 11.29, 5.973]}
          scale={[0.449, 0.449, 0.523]}
        />
        <mesh
          geometry={nodes.Cylinder092_Material001_0.geometry}
          material={materials["Material.001"]}
          position={[-240.869, 31.735, 11.54]}
          rotation={[-Math.PI / 2, Math.PI / 2, 0]}
          scale={24.392}
        />
        <mesh
          geometry={nodes.Cylinder091__0.geometry}
          material={materials["Cylinder.091__0"]}
          position={[-227.235, 10.113, 6.091]}
          scale={[0.044, 0.044, 1.373]}
        />
        <mesh
          geometry={nodes.Cylinder088_Material079_0.geometry}
          material={materials["Material.079"]}
          position={[-225.293, 3.322, 5.967]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[0.774, 0.774, 3.32]}
        />
        <mesh
          geometry={nodes.Cylinder087__0.geometry}
          material={materials["Cylinder.091__0"]}
          position={[-225.293, 1.506, 5.895]}
          scale={[1.336, 1.336, 1.752]}
        />
        <mesh
          geometry={nodes.Cylinder085_Material064_0.geometry}
          material={materials["Material.064"]}
          position={[11.013, 29.609, -37.541]}
          rotation={[-Math.PI / 2, Math.PI / 2, 0]}
          scale={[1.819, 1.819, 3.113]}
        />
        <mesh
          geometry={nodes.Cylinder084_Material064_0.geometry}
          material={materials["Material.064"]}
          position={[11.013, 30.021, 48.894]}
          rotation={[-Math.PI / 2, Math.PI / 2, 0]}
          scale={[1.819, 1.819, 3.113]}
        />
        <mesh
          geometry={nodes.Cylinder078__0.geometry}
          material={materials["Cylinder.091__0"]}
          position={[2.067, 10.366, -36.791]}
          scale={[0.18, 0.18, 1.474]}
        />
        <mesh
          geometry={nodes.Cylinder074_Material001_0.geometry}
          material={materials["Material.001"]}
          position={[-112.14, 43.408, 5.883]}
          rotation={[-Math.PI / 2, Math.PI / 2, 0]}
          scale={24.392}
        />
        <mesh
          geometry={nodes.Cylinder071_Material048_0.geometry}
          material={materials["Material.048"]}
          position={[11.852, 23.419, 47.166]}
          rotation={[Math.PI, -0.693, 0]}
          scale={0.247}
        />
        <mesh
          geometry={nodes.Cylinder069_Material039_0.geometry}
          material={materials["Material.039"]}
          position={[26.164, 1.708, 47.614]}
          rotation={[-1.237, 0, -Math.PI]}
          scale={0.084}
        />
        <mesh
          geometry={nodes.Cylinder068_Material039_0.geometry}
          material={materials["Material.039"]}
          position={[3.242, 1.708, 50.196]}
          rotation={[-1.905, 0, 0]}
          scale={0.084}
        />
        <mesh
          geometry={nodes.Cylinder066_Material039_0.geometry}
          material={materials["Material.039"]}
          position={[26.164, 1.708, -38.072]}
          rotation={[-1.237, 0, -Math.PI]}
          scale={0.084}
        />
        <mesh
          geometry={nodes.Cylinder064__0.geometry}
          material={materials["Cylinder.091__0"]}
          position={[2.067, 10.366, 48.894]}
          scale={[0.18, 0.18, 1.474]}
        />
        <mesh
          geometry={nodes.Cylinder063_Material039_0.geometry}
          material={materials["Material.039"]}
          position={[3.242, 1.708, -35.49]}
          rotation={[-1.905, 0, 0]}
          scale={0.084}
        />
        <mesh
          geometry={nodes.Cylinder062__0.geometry}
          material={materials["Cylinder.091__0"]}
          position={[12.802, 11.665, -36.791]}
          rotation={[Math.PI / 2, 0.084, 0]}
          scale={[-2.469, 2.469, 0.426]}
        />
        <mesh
          geometry={nodes.Cylinder060_Material046_0.geometry}
          material={materials["Material.046"]}
          position={[10.225, 10.263, -36.791]}
          rotation={[0, 0, -0.41]}
          scale={[0.54, 0.54, 1.717]}
        />
        <mesh
          geometry={nodes.Cylinder058__0.geometry}
          material={materials["Cylinder.091__0"]}
          position={[12.802, 11.665, 48.894]}
          rotation={[Math.PI / 2, 0.084, 0]}
          scale={[-2.469, 2.469, 0.426]}
        />
        <mesh
          geometry={nodes.Cylinder057_Material048_0.geometry}
          material={materials["Material.048"]}
          position={[13.629, 23.419, 47.501]}
          rotation={[Math.PI, 0.105, 0]}
          scale={0.247}
        />
        <mesh
          geometry={nodes.Cylinder056_Material046_0.geometry}
          material={materials["Material.046"]}
          position={[10.225, 10.263, 48.894]}
          rotation={[0, 0, -0.41]}
          scale={[0.54, 0.54, 1.717]}
        />
        <mesh
          geometry={nodes.Cylinder053_Material034_0.geometry}
          material={materials["Material.034"]}
          position={[14.519, 3.275, 48.894]}
          scale={[1.493, 1.493, 3.522]}
        />
        <mesh
          geometry={nodes.Cylinder051_Material034_0.geometry}
          material={materials["Material.034"]}
          position={[14.519, 3.275, -36.791]}
          scale={[1.493, 1.493, 3.522]}
        />
        <mesh
          geometry={nodes.Cylinder043__0.geometry}
          material={materials["Cylinder.091__0"]}
          position={[102.038, 68.428, 5.883]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[7.722, 5.345, 0.999]}
        />
        <mesh
          geometry={nodes.Cylinder041_Material001_0.geometry}
          material={materials["Material.001"]}
          position={[-240.869, 31.735, 11.54]}
          rotation={[-Math.PI / 2, Math.PI / 2, 0]}
          scale={24.392}
        />
        <mesh
          geometry={nodes.Cylinder040_Material002_0.geometry}
          material={materials["Material.002"]}
          position={[-112.14, 43.408, 5.883]}
          rotation={[-Math.PI / 2, Math.PI / 2, 0]}
          scale={24.392}
        />
        <mesh
          geometry={nodes.Cylinder037_Material001_0.geometry}
          material={materials["Material.001"]}
          position={[-112.14, 43.408, 5.883]}
          rotation={[-Math.PI / 2, Math.PI / 2, 0]}
          scale={24.392}
        />
        <mesh
          geometry={nodes.Cylinder036_Material001_0.geometry}
          material={materials["Material.001"]}
          position={[-112.14, 43.408, 5.883]}
          rotation={[-Math.PI / 2, Math.PI / 2, 0]}
          scale={24.392}
        />
        <mesh
          geometry={nodes.Cylinder034_Material001_0.geometry}
          material={materials["Material.001"]}
          position={[-112.14, 43.408, 5.883]}
          rotation={[-Math.PI / 2, Math.PI / 2, 0]}
          scale={24.392}
        />
        <mesh
          geometry={nodes.Cylinder033_Material001_0.geometry}
          material={materials["Material.001"]}
          position={[-112.14, 43.408, 5.883]}
          rotation={[-Math.PI / 2, Math.PI / 2, 0]}
          scale={24.392}
        />
        <mesh
          geometry={nodes.Cylinder032_Material001_0.geometry}
          material={materials["Material.001"]}
          position={[-112.14, 43.408, 5.883]}
          rotation={[-Math.PI / 2, Math.PI / 2, 0]}
          scale={24.392}
        />
        <mesh
          geometry={nodes.Cylinder031_Material001_0.geometry}
          material={materials["Material.001"]}
          position={[-112.14, 43.408, 5.883]}
          rotation={[-Math.PI / 2, Math.PI / 2, 0]}
          scale={24.392}
        />
        <mesh
          geometry={nodes.Cylinder028_Material007_0.geometry}
          material={materials["Material.007"]}
          position={[-60.923, 22.567, -70.331]}
          rotation={[Math.PI / 2, -Math.PI / 2, 0]}
          scale={[-3.886, 3.886, 2.446]}
        />
        <mesh
          geometry={nodes.Cylinder025_Material007_0.geometry}
          material={materials["Material.007"]}
          position={[-60.923, 22.438, 82.176]}
          rotation={[Math.PI / 2, -Math.PI / 2, 0]}
          scale={[-3.886, 3.886, 2.446]}
        />
        <mesh
          geometry={nodes.Cylinder011__0.geometry}
          material={materials["Cylinder.091__0"]}
          position={[254.433, 50.854, 5.876]}
          scale={[25.961, 2.435, 19.503]}
        />
        <mesh
          geometry={nodes.Cylinder010__0.geometry}
          material={materials["Cylinder.091__0"]}
          position={[237.768, 69.59, 5.876]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[35.327, 0.441, 3.247]}
        />
        <mesh
          geometry={nodes.Cylinder007_Material001_0.geometry}
          material={materials["Material.001"]}
          position={[-112.14, 43.408, 5.883]}
          rotation={[-Math.PI / 2, Math.PI / 2, 0]}
          scale={24.392}
        />
        <mesh
          geometry={nodes.Cylinder003_Material003_0.geometry}
          material={materials["Material.003"]}
          position={[-112.14, 43.408, 5.883]}
          rotation={[-Math.PI / 2, Math.PI / 2, 0]}
          scale={24.392}
        />
        <mesh
          geometry={nodes.Cylinder002_Material002_0.geometry}
          material={materials["Material.002"]}
          position={[-112.14, 43.408, 5.883]}
          rotation={[-Math.PI / 2, Math.PI / 2, 0]}
          scale={24.392}
        />
        <mesh
          geometry={nodes.Cylinder_Material002_0.geometry}
          material={materials["Material.002"]}
          position={[-112.14, 43.408, 5.883]}
          rotation={[-Math.PI / 2, Math.PI / 2, 0]}
          scale={24.392}
        />
        <mesh
          geometry={nodes.Cube052_Material078_0.geometry}
          material={materials["Material.078"]}
          position={[-229.594, 14.756, 5.958]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={0.536}
        />
        <mesh
          geometry={nodes.Cube049_Material082_0.geometry}
          material={materials["Material.082"]}
          position={[-229.104, 15.885, 5.483]}
          rotation={[-Math.PI / 2, -0.797, 0]}
          scale={[0.404, 0.106, 0.404]}
        />
        <mesh
          geometry={nodes.Cube048__0.geometry}
          material={materials["Cylinder.091__0"]}
          position={[-225.98, 15.863, 3.924]}
          rotation={[-Math.PI / 2, 0, -Math.PI]}
          scale={[0.094, 0.476, 1.565]}
        />
        <mesh
          geometry={nodes.Cube047__0.geometry}
          material={materials["Cylinder.091__0"]}
          position={[-225.98, 15.863, 8.015]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[0.094, 0.476, 1.565]}
        />
        <mesh
          geometry={nodes.Cube046_Material081_0.geometry}
          material={materials["Material.081"]}
          position={[-225.335, 18.305, 5.974]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[0.852, 5.363, 0.217]}
        />
        <mesh
          geometry={nodes.Cube044_Material078_0.geometry}
          material={materials["Material.078"]}
          position={[-229.594, 15.867, 5.958]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[0.536, 0.536, 0.742]}
        />
        <mesh
          geometry={nodes.Cube043_Material068_0.geometry}
          material={materials["Material.068"]}
          position={[-227.446, 8.532, 5.138]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={[-0.315, 0.315, 0.165]}
        />
        <mesh
          geometry={nodes.Cube041_Material069_0.geometry}
          material={materials["Material.069"]}
          position={[-227.943, 9.179, 6.045]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[0.696, 1.254, 0.696]}
        />
        <mesh
          geometry={nodes.Cube040_Material071_0.geometry}
          material={materials["Material.071"]}
          position={[-225.67, 8.68, 6.063]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[2.625, 1.851, 0.102]}
        />
        <mesh
          geometry={nodes.Cube039_Material049_0.geometry}
          material={materials["Material.049"]}
          position={[8.646, 22.817, 43.25]}
          rotation={[-Math.PI / 2, 0, 0.709]}
          scale={0.219}
        />
        <mesh
          geometry={nodes.Cube038_Material074_0.geometry}
          material={materials["Material.074"]}
          position={[-224.465, 9.838, 5.961]}
          rotation={[-Math.PI / 2, 0.547, 0]}
          scale={[0.399, 0.734, 0.399]}
        />
        <mesh
          geometry={nodes.Cube037_Material049_0.geometry}
          material={materials["Material.049"]}
          position={[14.191, 22.817, 42.471]}
          rotation={[-Math.PI / 2, 0, -0.088]}
          scale={0.219}
        />
        <mesh
          geometry={nodes.Cube036_Material022_0.geometry}
          material={materials["Material.022"]}
          position={[14.735, 1.264, -38.058]}
          rotation={[-Math.PI / 2, 0, -Math.PI]}
          scale={[12.062, 0.271, 0.472]}
        />
        <mesh
          geometry={nodes.Cube034_Material022_0.geometry}
          material={materials["Material.022"]}
          position={[14.671, 1.264, -35.503]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[12.062, 0.271, 0.472]}
        />
        <mesh
          geometry={nodes.Cube032_Material022_0.geometry}
          material={materials["Material.022"]}
          position={[14.735, 1.264, 47.627]}
          rotation={[-Math.PI / 2, 0, -Math.PI]}
          scale={[12.062, 0.271, 0.472]}
        />
        <mesh
          geometry={nodes.Cube028_Material022_0.geometry}
          material={materials["Material.022"]}
          position={[14.671, 1.264, 50.182]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[12.062, 0.271, 0.472]}
        />
        <mesh
          geometry={nodes.Cube024_Material041_0.geometry}
          material={materials["Material.041"]}
          position={[5.548, 9.665, 48.894]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[0.371, 0.631, 0.371]}
        />
        <mesh
          geometry={nodes.Cube021_Material041_0.geometry}
          material={materials["Material.041"]}
          position={[5.548, 9.665, -36.791]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[0.371, 0.631, 0.371]}
        />
        <mesh
          geometry={nodes.Cube019_Material019_0.geometry}
          material={materials["Material.019"]}
          position={[19.498, 32.636, -60.964]}
          rotation={[-1.378, 0.047, 0]}
          scale={[2.514, 1.739, 2.514]}
        />
        <mesh
          geometry={nodes.Cube018_Material017_0.geometry}
          material={materials["Material.017"]}
          position={[33.353, 38.333, -103.422]}
          rotation={[-1.361, 0.047, 0]}
          scale={[2.514, 1.739, 2.514]}
        />
        <mesh
          geometry={nodes.Cube017_Material017_0.geometry}
          material={materials["Material.017"]}
          position={[47.748, 43.349, -146.308]}
          rotation={[-1.377, 0.047, 0]}
          scale={[2.514, 1.739, 2.514]}
        />
        <mesh
          geometry={nodes.Cube016_Material019_0.geometry}
          material={materials["Material.019"]}
          position={[19.498, 32.636, 72.72]}
          rotation={[-1.64, 0.047, 0]}
          scale={[2.514, 1.739, 2.514]}
        />
        <mesh
          geometry={nodes.Cube015_Material017_0.geometry}
          material={materials["Material.017"]}
          position={[47.748, 43.85, 157.827]}
          rotation={[-1.713, 0.047, 0]}
          scale={[2.514, 1.739, 2.514]}
        />
        <mesh
          geometry={nodes.Cube014_Material018_0.geometry}
          material={materials["Material.018"]}
          position={[32.622, 37.769, 115.154]}
          rotation={[-1.64, 0.047, 0]}
          scale={[2.514, 1.739, 2.514]}
        />
        <mesh
          geometry={nodes.Cube010__0.geometry}
          material={materials["Cylinder.091__0"]}
          position={[-94.093, 69.648, 5.883]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={[2.833, 0.172, 2.833]}
        />
        <mesh
          geometry={nodes.Cube004_Material015_0.geometry}
          material={materials["Material.015"]}
          position={[-50.906, 31.043, -54.881]}
          rotation={[-0.943, 0, 0]}
          scale={[-5.326, 0.079, 1.602]}
        />
        <mesh
          geometry={nodes.Cube003_Material084_0.geometry}
          material={materials["Material.084"]}
          position={[-51.102, 22.567, -70.331]}
          rotation={[2.967, 0, 0]}
          scale={[0.227, 0.76, 13.759]}
        />
        <mesh
          geometry={nodes.Cube002_Material015_0.geometry}
          material={materials["Material.015"]}
          position={[-50.906, 30.914, 66.521]}
          rotation={[-2.514, 0, 0]}
          scale={[-5.326, 0.079, 1.602]}
        />
        <mesh
          geometry={nodes.Cube001_Material084_0.geometry}
          material={materials["Material.084"]}
          position={[-51.102, 22.438, 82.176]}
          rotation={[2.967, 0, 0]}
          scale={[0.227, 0.76, 13.759]}
        />
        <mesh
          geometry={nodes.Cylinder004__0.geometry}
          material={materials["Cylinder.091__0"]}
          position={[237.768, 69.59, 5.876]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[35.327, 0.441, 3.247]}
        />
      </group>
    </group>
  )
}
