/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 plane.gltf 
Author: mamont nikita (https://sketchfab.com/mamontnikita62)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/boeing-777-aeroflot-32c3ca1705bc4c05b5ea3b9052241491
Title: boeing 777 aeroflot
*/

import React from "react"
import { useGLTF } from "@react-three/drei"

export default function Model(props) {
  const { nodes, materials } = useGLTF("/plane.gltf")
  return (
    <group {...props} dispose={null}>
      <group scale={0.025}>
        <group
          position={[0, 358.244, -658.285]}
          rotation={[-Math.PI / 2, 0, Math.PI]}
          scale={[0.108, 0.11, 0.171]}
        >
          <mesh
            geometry={nodes["Component#96_004_Color_000_0"].geometry}
            material={materials.Color_000}
            position={[-3.346, -56.005, -58.661]}
          />
        </group>
        <group
          position={[0, 95.6, -563.44]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={[-0.108, 0.11, 0.171]}
        >
          <mesh
            geometry={nodes["Component#96_003_Color_000_0"].geometry}
            material={materials.Color_000}
            position={[-3.346, -56.004, -58.661]}
          />
        </group>
        <group
          position={[0, 514.378, -1179.49]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[1, 1.03, 1.015]}
        >
          <group position={[-17.876, -341.951, -238.409]}>
            <mesh
              geometry={
                nodes["Component#2_001_777_vertical_stabilizer3_0"].geometry
              }
              material={materials["777_vertical_stabilizer3"]}
            />
            <mesh
              geometry={nodes["Component#2_001_Color_0041_0"].geometry}
              material={materials.Color_0041}
            />
            <mesh
              geometry={nodes["Component#2_001_Color_0032_0"].geometry}
              material={materials.Color_0032}
            />
            <mesh
              geometry={nodes["Component#2_001_Color_005_0"].geometry}
              material={materials.Color_005}
            />
            <mesh
              geometry={nodes["Component#2_001_Color_A061_0"].geometry}
              material={materials.Color_A061}
            />
            <mesh
              geometry={nodes["Component#2_001_Color_A021_0"].geometry}
              material={materials.Color_A021}
            />
            <mesh
              geometry={nodes["Component#2_001_Color_008_0"].geometry}
              material={materials.Color_008}
            />
            <mesh
              geometry={nodes["Component#2_001_Color_0072_0"].geometry}
              material={materials.Color_0072}
            />
            <mesh
              geometry={nodes["Component#2_001_Color_0071_0"].geometry}
              material={materials.Color_0071}
            />
            <mesh
              geometry={nodes["Component#2_001_Color_0043_0"].geometry}
              material={materials.Color_0043}
            />
            <mesh
              geometry={nodes["Component#2_001_Color_0061_0"].geometry}
              material={materials.Color_0061}
            />
            <mesh
              geometry={nodes["Component#2_001_Color_0062_0"].geometry}
              material={materials.Color_0062}
            />
            <mesh
              geometry={nodes["Component#2_001_Color_A01_0"].geometry}
              material={materials.Color_A01}
            />
            <mesh
              geometry={nodes["Component#2_001_Color_A011_0"].geometry}
              material={materials.Color_A011}
            />
            <mesh
              geometry={nodes["Component#2_001_Color_I11_0"].geometry}
              material={materials.Color_I11}
            />
            <mesh
              geometry={nodes["Component#2_001_Color_0082_0"].geometry}
              material={materials.Color_0082}
            />
            <mesh
              geometry={nodes["Component#2_001_Color_0042_0"].geometry}
              material={materials.Color_0042}
            />
            <mesh
              geometry={nodes["Component#2_001_Color_0091_0"].geometry}
              material={materials.Color_0091}
            />
            <mesh
              geometry={nodes["Component#2_001_Color_A02_0"].geometry}
              material={materials.Color_A02}
            />
            <mesh
              geometry={nodes["Component#2_001_Color_0073_0"].geometry}
              material={materials.Color_0073}
            />
            <mesh
              geometry={nodes["Component#2_001_Color_0031_0"].geometry}
              material={materials.Color_0031}
            />
            <mesh
              geometry={nodes["Component#2_001_Color_0033_0"].geometry}
              material={materials.Color_0033}
            />
            <mesh
              geometry={nodes["Component#2_001_Color_0044_0"].geometry}
              material={materials.Color_0044}
            />
            <mesh
              geometry={nodes["Component#2_001_Color_0063_0"].geometry}
              material={materials.Color_0063}
            />
            <mesh
              geometry={nodes["Component#2_001_Color_001_0"].geometry}
              material={materials.Color_001}
            />
            <mesh
              geometry={nodes["Component#2_001_Color_0074_0"].geometry}
              material={materials.Color_0074}
            />
            <mesh
              geometry={nodes["Component#2_001_Color_004_0"].geometry}
              material={materials.Color_004}
            />
          </group>
        </group>
        <group
          position={[0, 358.244, 553.667]}
          rotation={[-Math.PI / 2, 0, Math.PI]}
          scale={[0.108, 0.11, 0.171]}
        >
          <mesh
            geometry={nodes["Component#96_002_Color_000_0"].geometry}
            material={materials.Color_000}
            position={[-3.346, -56.004, -58.661]}
          />
        </group>
        <group
          position={[0, 354.763, -742.799]}
          rotation={[-Math.PI / 2, 0, Math.PI]}
          scale={[0.054, 0.055, 0.085]}
        >
          <mesh
            geometry={nodes["Component#96_001_Color_000_0"].geometry}
            material={materials.Color_000}
            position={[-3.346, -56.005, -58.661]}
          />
        </group>
        <group
          position={[400.535, 141.08, 406.073]}
          rotation={[-1.399, 0.739, -2.688]}
          scale={[-0.736, 1.059, 1.003]}
        >
          <mesh
            geometry={nodes.Group_111_Material6_0.geometry}
            material={materials.Material6}
            position={[-5.139, -10.237, -20.74]}
          />
        </group>
        <group
          position={[414.691, 104.12, 406.073]}
          rotation={[2.265, 1.456, -0.134]}
          scale={[-0.737, 1.077, 0.985]}
        >
          <mesh
            geometry={nodes.Group_110_Material6_0.geometry}
            material={materials.Material6}
            position={[-5.139, -10.237, -20.74]}
          />
        </group>
        <group
          position={[411.857, 94.107, 406.073]}
          rotation={[2.043, 1.24, 0.113]}
          scale={[-0.737, 1.077, 0.985]}
        >
          <mesh
            geometry={nodes.Group_109_Material6_0.geometry}
            material={materials.Material6}
            position={[-5.139, -10.237, -20.74]}
          />
        </group>
        <group
          position={[382.073, 149.177, 406.073]}
          rotation={[-1.543, 0.148, -2.579]}
          scale={[-0.736, 1.052, 1.009]}
        >
          <mesh
            geometry={nodes.Group_108_Material6_0.geometry}
            material={materials.Material6}
            position={[-5.139, -10.238, -20.74]}
          />
        </group>
        <group
          position={[391.837, 146.376, 406.073]}
          rotation={[-1.48, 0.449, -2.613]}
          scale={[-0.736, 1.054, 1.008]}
        >
          <mesh
            geometry={nodes.Group_107_Material6_0.geometry}
            material={materials.Material6}
            position={[-5.139, -10.238, -20.74]}
          />
        </group>
        <group
          position={[407.574, 133.648, 406.073]}
          rotation={[-1.286, 1.007, -2.815]}
          scale={[-0.736, 1.065, 0.996]}
        >
          <mesh
            geometry={nodes.Group_106_Material6_0.geometry}
            material={materials.Material6}
            position={[-5.139, -10.237, -20.74]}
          />
        </group>
        <group
          position={[412.474, 124.588, 406.073]}
          rotation={[-1.145, 1.247, -2.983]}
          scale={[-0.737, 1.071, 0.991]}
        >
          <mesh
            geometry={nodes.Group_105_Material6_0.geometry}
            material={materials.Material6}
            position={[-5.139, -10.237, -20.74]}
          />
        </group>
        <group
          position={[414.901, 114.516, 406.073]}
          rotation={[-1.095, 1.467, -3.058]}
          scale={[-0.737, 1.075, 0.987]}
        >
          <mesh
            geometry={nodes.Group_104_Material6_0.geometry}
            material={materials.Material6}
            position={[-5.139, -10.237, -20.74]}
          />
        </group>
        <group
          position={[406.668, 85.257, 406.073]}
          rotation={[1.869, 1.006, 0.312]}
          scale={[-0.737, 1.074, 0.988]}
        >
          <mesh
            geometry={nodes.Group_103_Material6_0.geometry}
            material={materials.Material6}
            position={[-5.139, -10.237, -20.74]}
          />
        </group>
        <group
          position={[399.353, 77.963, 406.073]}
          rotation={[1.746, 0.742, 0.446]}
          scale={[-0.737, 1.069, 0.993]}
        >
          <mesh
            geometry={nodes.Group_102_Material6_0.geometry}
            material={materials.Material6}
            position={[-5.139, -10.237, -20.74]}
          />
        </group>
        <group
          position={[380.595, 70.222, 406.073]}
          rotation={[1.601, 0.159, 0.561]}
          scale={[-0.736, 1.056, 1.005]}
        >
          <mesh
            geometry={nodes.Group_101_Material6_0.geometry}
            material={materials.Material6}
            position={[-5.139, -10.238, -20.74]}
          />
        </group>
        <group
          position={[370.43, 70.303, 406.073]}
          rotation={[1.544, -0.145, 0.563]}
          scale={[-0.736, 1.052, 1.009]}
        >
          <mesh
            geometry={nodes.Group_100_Material6_0.geometry}
            material={materials.Material6}
            position={[-5.139, -10.237, -20.74]}
          />
        </group>
        <group
          position={[360.657, 73.073, 406.073]}
          rotation={[1.481, -0.446, 0.529]}
          scale={[-0.736, 1.054, 1.008]}
        >
          <mesh
            geometry={nodes.Group_099_Material6_0.geometry}
            material={materials.Material6}
            position={[-5.139, -10.237, -20.74]}
          />
        </group>
        <group
          position={[390.461, 72.835, 406.073]}
          rotation={[1.664, 0.456, 0.524]}
          scale={[-0.736, 1.062, 0.999]}
        >
          <mesh
            geometry={nodes.Group_098_Material6_0.geometry}
            material={materials.Material6}
            position={[-5.139, -10.237, -20.74]}
          />
        </group>
        <group
          position={[344.882, 85.75, 406.073]}
          rotation={[1.288, -1.004, 0.328]}
          scale={[-0.736, 1.065, 0.996]}
        >
          <mesh
            geometry={nodes.Group_097_Material6_0.geometry}
            material={materials.Material6}
            position={[-5.139, -10.238, -20.74]}
          />
        </group>
        <group
          position={[351.943, 78.341, 406.073]}
          rotation={[1.4, -0.736, 0.454]}
          scale={[-0.736, 1.059, 1.003]}
        >
          <mesh
            geometry={nodes.Group_096_Material6_0.geometry}
            material={materials.Material6}
            position={[-5.139, -10.237, -20.74]}
          />
        </group>
        <group
          position={[339.91, 94.91, 406.073]}
          rotation={[1.145, -1.247, 0.158]}
          scale={[-0.737, 1.071, 0.991]}
        >
          <mesh
            geometry={nodes.Group_095_Material6_0.geometry}
            material={materials.Material6}
            position={[-5.139, -10.237, -20.74]}
          />
        </group>
        <group
          position={[337.482, 104.981, 406.073]}
          rotation={[1.095, -1.467, 0.084]}
          scale={[-0.737, 1.075, 0.987]}
        >
          <mesh
            geometry={nodes.Group_094_Material6_0.geometry}
            material={materials.Material6}
            position={[-5.139, -10.237, -20.74]}
          />
        </group>
        <group
          position={[340.527, 125.391, 406.073]}
          rotation={[-2.043, -1.24, -3.029]}
          scale={[-0.737, 1.077, 0.985]}
        >
          <mesh
            geometry={nodes.Group_093_Material6_0.geometry}
            material={materials.Material6}
            position={[-5.139, -10.237, -20.74]}
          />
        </group>
        <group
          position={[337.692, 115.378, 406.073]}
          rotation={[-2.265, -1.456, 3.008]}
          scale={[-0.737, 1.077, 0.985]}
        >
          <mesh
            geometry={nodes.Group_092_Material6_0.geometry}
            material={materials.Material6}
            position={[-5.139, -10.237, -20.74]}
          />
        </group>
        <group
          position={[345.791, 134.337, 406.073]}
          rotation={[-1.867, -1.003, -2.828]}
          scale={[-0.737, 1.074, 0.988]}
        >
          <mesh
            geometry={nodes.Group_091_Material6_0.geometry}
            material={materials.Material6}
            position={[-5.139, -10.237, -20.74]}
          />
        </group>
        <group
          position={[353.127, 141.609, 406.073]}
          rotation={[-1.745, -0.738, -2.694]}
          scale={[-0.737, 1.069, 0.993]}
        >
          <mesh
            geometry={nodes.Group_090_Material6_0.geometry}
            material={materials.Material6}
            position={[-5.139, -10.237, -20.74]}
          />
        </group>
        <group
          position={[362.036, 146.709, 406.073]}
          rotation={[-1.663, -0.453, -2.617]}
          scale={[-0.736, 1.062, 0.999]}
        >
          <mesh
            geometry={nodes.Group_089_Material6_0.geometry}
            material={materials.Material6}
            position={[-5.139, -10.238, -20.74]}
          />
        </group>
        <group
          position={[371.908, 149.29, 406.073]}
          rotation={[-1.6, -0.155, -2.58]}
          scale={[-0.736, 1.056, 1.005]}
        >
          <mesh
            geometry={nodes.Group_088_Material6_0.geometry}
            material={materials.Material6}
            position={[-5.139, -10.237, -20.74]}
          />
        </group>
        <group
          position={[376.192, 109.749, 415.262]}
          rotation={[-Math.PI / 2, -0.137, Math.PI]}
          scale={[-0.985, 0.696, 1.009]}
        >
          <group position={[-60.586, -22.651, -60.586]}>
            <mesh
              geometry={
                nodes.Generic_Turbofan_Fan_002_skp_front_default_0.geometry
              }
              material={materials.skp_front_default}
            />
            <mesh
              geometry={nodes.Generic_Turbofan_Fan_002_Material2_0.geometry}
              material={materials.Material2}
            />
            <mesh
              geometry={nodes.Generic_Turbofan_Fan_002_Material5_0.geometry}
              material={materials.Material5}
            />
          </group>
        </group>
        <group
          position={[377.449, 111.043, 450.475]}
          rotation={[-Math.PI / 2, -0.137, Math.PI / 2]}
          scale={[0.886, 0.978, 1.002]}
        >
          <mesh
            geometry={nodes.Group_087_Color_002_0.geometry}
            material={materials.Color_002}
            position={[-4.81, -79.615, -79.615]}
          />
        </group>
        <group
          position={[378.194, 110.483, 187.379]}
          rotation={[-Math.PI / 2, -0.137, Math.PI / 2]}
          scale={[1.226, 0.985, 1.009]}
        >
          <mesh
            geometry={nodes.Group_086_Color_004_0.geometry}
            material={materials.Color_004}
            position={[-57.587, -47.932, -47.932]}
          />
        </group>
        <group
          position={[378.396, 110.273, 319.519]}
          rotation={[-Math.PI / 2, -0.137, Math.PI / 2]}
          scale={[0.939, 1.036, 1.062]}
        >
          <mesh
            geometry={nodes.Group_084_0133_Gray_0.geometry}
            material={materials["0133_Gray"]}
            position={[-140.568, -62.641, -62.682]}
          />
        </group>
        <group
          position={[367.706, 181.123, 211.189]}
          rotation={[-Math.PI / 2, 0, Math.PI]}
          scale={[0.98, 1.006, 1]}
        >
          <group position={[-17.523, -194.198, -31.227]}>
            <mesh
              geometry={nodes.Group_083_skp_front_default_0.geometry}
              material={materials.skp_front_default}
            />
            <mesh
              geometry={nodes.Group_083_Color_002_0.geometry}
              material={materials.Color_002}
            />
          </group>
        </group>
        <group
          position={[376.917, 116.757, 230.985]}
          rotation={[-Math.PI / 2, 0, Math.PI]}
          scale={[0.98, 1.006, 1]}
        >
          <group position={[-803.736, -1487.417, -116.789]}>
            <mesh
              geometry={
                nodes["Rolls_Royce_Trent_800_(With_Blades)#2_004_Color_002_0"]
                  .geometry
              }
              material={materials.Color_002}
            />
            <mesh
              geometry={
                nodes["Rolls_Royce_Trent_800_(With_Blades)#2_004_Material4_0"]
                  .geometry
              }
              material={materials.Material4}
            />
            <mesh
              geometry={
                nodes["Rolls_Royce_Trent_800_(With_Blades)#2_004_0133_Gray_0"]
                  .geometry
              }
              material={materials["0133_Gray"]}
            />
            <mesh
              geometry={
                nodes["Rolls_Royce_Trent_800_(With_Blades)#2_004_Color_0041_0"]
                  .geometry
              }
              material={materials.Color_0041}
            />
            <mesh
              geometry={
                nodes["Rolls_Royce_Trent_800_(With_Blades)#2_004_Color_A06_0"]
                  .geometry
              }
              material={materials.Color_A06}
            />
          </group>
        </group>
        <group
          position={[-396.274, 141.08, 406.073]}
          rotation={[-1.399, -0.739, 2.688]}
          scale={[0.736, 1.059, 1.003]}
        >
          <mesh
            geometry={nodes.Group_082_Material6_0.geometry}
            material={materials.Material6}
            position={[-5.139, -10.237, -20.74]}
          />
        </group>
        <group
          position={[-410.431, 104.12, 406.073]}
          rotation={[2.265, -1.456, 0.134]}
          scale={[0.737, 1.077, 0.985]}
        >
          <mesh
            geometry={nodes.Group_081_Material6_0.geometry}
            material={materials.Material6}
            position={[-5.139, -10.237, -20.74]}
          />
        </group>
        <group
          position={[-407.597, 94.107, 406.073]}
          rotation={[2.043, -1.24, -0.113]}
          scale={[0.737, 1.077, 0.985]}
        >
          <mesh
            geometry={nodes.Group_080_Material6_0.geometry}
            material={materials.Material6}
            position={[-5.139, -10.237, -20.74]}
          />
        </group>
        <group
          position={[-377.813, 149.177, 406.073]}
          rotation={[-1.543, -0.148, 2.579]}
          scale={[0.736, 1.052, 1.009]}
        >
          <mesh
            geometry={nodes.Group_079_Material6_0.geometry}
            material={materials.Material6}
            position={[-5.139, -10.237, -20.74]}
          />
        </group>
        <group
          position={[-387.577, 146.376, 406.073]}
          rotation={[-1.48, -0.449, 2.613]}
          scale={[0.736, 1.054, 1.008]}
        >
          <mesh
            geometry={nodes.Group_078_Material6_0.geometry}
            material={materials.Material6}
            position={[-5.139, -10.238, -20.74]}
          />
        </group>
        <group
          position={[-403.313, 133.648, 406.073]}
          rotation={[-1.286, -1.007, 2.815]}
          scale={[0.736, 1.065, 0.996]}
        >
          <mesh
            geometry={nodes.Group_077_Material6_0.geometry}
            material={materials.Material6}
            position={[-5.139, -10.237, -20.74]}
          />
        </group>
        <group
          position={[-408.214, 124.588, 406.073]}
          rotation={[-1.145, -1.247, 2.983]}
          scale={[0.737, 1.071, 0.991]}
        >
          <mesh
            geometry={nodes.Group_076_Material6_0.geometry}
            material={materials.Material6}
            position={[-5.139, -10.237, -20.74]}
          />
        </group>
        <group
          position={[-410.641, 114.516, 406.073]}
          rotation={[-1.095, -1.467, 3.058]}
          scale={[0.737, 1.075, 0.987]}
        >
          <mesh
            geometry={nodes.Group_075_Material6_0.geometry}
            material={materials.Material6}
            position={[-5.139, -10.237, -20.74]}
          />
        </group>
        <group
          position={[-402.407, 85.257, 406.073]}
          rotation={[1.869, -1.006, -0.312]}
          scale={[0.737, 1.074, 0.988]}
        >
          <mesh
            geometry={nodes.Group_074_Material6_0.geometry}
            material={materials.Material6}
            position={[-5.139, -10.237, -20.74]}
          />
        </group>
        <group
          position={[-395.093, 77.963, 406.073]}
          rotation={[1.746, -0.742, -0.446]}
          scale={[0.737, 1.069, 0.993]}
        >
          <mesh
            geometry={nodes.Group_073_Material6_0.geometry}
            material={materials.Material6}
            position={[-5.139, -10.237, -20.74]}
          />
        </group>
        <group
          position={[-376.335, 70.222, 406.073]}
          rotation={[1.601, -0.159, -0.561]}
          scale={[0.736, 1.056, 1.005]}
        >
          <mesh
            geometry={nodes.Group_072_Material6_0.geometry}
            material={materials.Material6}
            position={[-5.139, -10.237, -20.74]}
          />
        </group>
        <group
          position={[-366.17, 70.303, 406.073]}
          rotation={[1.544, 0.145, -0.563]}
          scale={[0.736, 1.052, 1.009]}
        >
          <mesh
            geometry={nodes.Group_071_Material6_0.geometry}
            material={materials.Material6}
            position={[-5.139, -10.237, -20.74]}
          />
        </group>
        <group
          position={[-356.397, 73.073, 406.073]}
          rotation={[1.481, 0.446, -0.529]}
          scale={[0.736, 1.054, 1.008]}
        >
          <mesh
            geometry={nodes.Group_070_Material6_0.geometry}
            material={materials.Material6}
            position={[-5.139, -10.237, -20.74]}
          />
        </group>
        <group
          position={[-386.2, 72.835, 406.073]}
          rotation={[1.664, -0.456, -0.524]}
          scale={[0.736, 1.062, 0.999]}
        >
          <mesh
            geometry={nodes.Group_069_Material6_0.geometry}
            material={materials.Material6}
            position={[-5.139, -10.237, -20.74]}
          />
        </group>
        <group
          position={[-340.621, 85.75, 406.073]}
          rotation={[1.288, 1.004, -0.328]}
          scale={[0.736, 1.065, 0.996]}
        >
          <mesh
            geometry={nodes.Group_068_Material6_0.geometry}
            material={materials.Material6}
            position={[-5.139, -10.237, -20.74]}
          />
        </group>
        <group
          position={[-347.683, 78.341, 406.073]}
          rotation={[1.4, 0.736, -0.454]}
          scale={[0.736, 1.059, 1.003]}
        >
          <mesh
            geometry={nodes.Group_067_Material6_0.geometry}
            material={materials.Material6}
            position={[-5.139, -10.237, -20.74]}
          />
        </group>
        <group
          position={[-335.649, 94.91, 406.073]}
          rotation={[1.145, 1.247, -0.158]}
          scale={[0.737, 1.071, 0.991]}
        >
          <mesh
            geometry={nodes.Group_066_Material6_0.geometry}
            material={materials.Material6}
            position={[-5.139, -10.237, -20.74]}
          />
        </group>
        <group
          position={[-333.222, 104.981, 406.073]}
          rotation={[1.095, 1.467, -0.084]}
          scale={[0.737, 1.075, 0.987]}
        >
          <mesh
            geometry={nodes.Group_065_Material6_0.geometry}
            material={materials.Material6}
            position={[-5.139, -10.237, -20.74]}
          />
        </group>
        <group
          position={[-336.266, 125.391, 406.073]}
          rotation={[-2.043, 1.24, 3.029]}
          scale={[0.737, 1.077, 0.985]}
        >
          <mesh
            geometry={nodes.Group_064_Material6_0.geometry}
            material={materials.Material6}
            position={[-5.139, -10.237, -20.74]}
          />
        </group>
        <group
          position={[-333.432, 115.378, 406.073]}
          rotation={[-2.265, 1.456, -3.008]}
          scale={[0.737, 1.077, 0.985]}
        >
          <mesh
            geometry={nodes.Group_063_Material6_0.geometry}
            material={materials.Material6}
            position={[-5.139, -10.237, -20.74]}
          />
        </group>
        <group
          position={[-341.531, 134.337, 406.073]}
          rotation={[-1.867, 1.003, 2.828]}
          scale={[0.737, 1.074, 0.988]}
        >
          <mesh
            geometry={nodes.Group_062_Material6_0.geometry}
            material={materials.Material6}
            position={[-5.139, -10.237, -20.74]}
          />
        </group>
        <group
          position={[-348.867, 141.609, 406.073]}
          rotation={[-1.745, 0.738, 2.694]}
          scale={[0.737, 1.069, 0.993]}
        >
          <mesh
            geometry={nodes.Group_061_Material6_0.geometry}
            material={materials.Material6}
            position={[-5.139, -10.237, -20.74]}
          />
        </group>
        <group
          position={[-357.775, 146.709, 406.073]}
          rotation={[-1.663, 0.453, 2.617]}
          scale={[0.736, 1.062, 0.999]}
        >
          <mesh
            geometry={nodes.Group_060_Material6_0.geometry}
            material={materials.Material6}
            position={[-5.139, -10.237, -20.74]}
          />
        </group>
        <group
          position={[-367.648, 149.29, 406.073]}
          rotation={[-1.6, 0.155, 2.58]}
          scale={[0.736, 1.056, 1.005]}
        >
          <mesh
            geometry={nodes.Group_059_Material6_0.geometry}
            material={materials.Material6}
            position={[-5.139, -10.237, -20.74]}
          />
        </group>
        <group
          position={[-371.931, 109.749, 415.262]}
          rotation={[-Math.PI / 2, 0.137, Math.PI]}
          scale={[0.985, 0.696, 1.009]}
        >
          <group position={[-60.586, -22.651, -60.586]}>
            <mesh
              geometry={
                nodes.Generic_Turbofan_Fan_001_skp_front_default_0.geometry
              }
              material={materials.skp_front_default}
            />
            <mesh
              geometry={nodes.Generic_Turbofan_Fan_001_Material2_0.geometry}
              material={materials.Material2}
            />
            <mesh
              geometry={nodes.Generic_Turbofan_Fan_001_Material5_0.geometry}
              material={materials.Material5}
            />
          </group>
        </group>
        <group
          position={[-373.189, 111.043, 450.475]}
          rotation={[-Math.PI / 2, 0.137, -Math.PI / 2]}
          scale={[-0.886, 0.978, 1.002]}
        >
          <mesh
            geometry={nodes.Group_058_Color_002_0.geometry}
            material={materials.Color_002}
            position={[-4.81, -79.615, -79.615]}
          />
        </group>
        <group
          position={[-373.933, 110.483, 187.379]}
          rotation={[-Math.PI / 2, 0.137, -Math.PI / 2]}
          scale={[-1.226, 0.985, 1.009]}
        >
          <mesh
            geometry={nodes.Group_057_Color_004_0.geometry}
            material={materials.Color_004}
            position={[-57.587, -47.932, -47.932]}
          />
        </group>
        <group
          position={[-374.136, 110.273, 319.519]}
          rotation={[-Math.PI / 2, 0.137, -Math.PI / 2]}
          scale={[-0.939, 1.036, 1.062]}
        >
          <mesh
            geometry={nodes.Group_055_0133_Gray_0.geometry}
            material={materials["0133_Gray"]}
            position={[-140.568, -62.641, -62.682]}
          />
        </group>
        <group
          position={[-363.445, 181.123, 211.189]}
          rotation={[-Math.PI / 2, 0, Math.PI]}
          scale={[-0.98, 1.006, 1]}
        >
          <group position={[-17.523, -194.198, -31.227]}>
            <mesh
              geometry={nodes.Group_054_skp_front_default_0.geometry}
              material={materials.skp_front_default}
            />
            <mesh
              geometry={nodes.Group_054_Color_002_0.geometry}
              material={materials.Color_002}
            />
          </group>
        </group>
        <group
          position={[-372.657, 116.756, 230.985]}
          rotation={[-Math.PI / 2, 0, Math.PI]}
          scale={[-0.98, 1.006, 1]}
        >
          <group position={[-803.736, -1487.417, -116.789]}>
            <mesh
              geometry={
                nodes["Rolls_Royce_Trent_800_(With_Blades)#2_001_Color_002_0"]
                  .geometry
              }
              material={materials.Color_002}
            />
            <mesh
              geometry={
                nodes["Rolls_Royce_Trent_800_(With_Blades)#2_001_Material4_0"]
                  .geometry
              }
              material={materials.Material4}
            />
            <mesh
              geometry={
                nodes["Rolls_Royce_Trent_800_(With_Blades)#2_001_0133_Gray_0"]
                  .geometry
              }
              material={materials["0133_Gray"]}
            />
            <mesh
              geometry={
                nodes["Rolls_Royce_Trent_800_(With_Blades)#2_001_Color_0041_0"]
                  .geometry
              }
              material={materials.Color_0041}
            />
            <mesh
              geometry={
                nodes["Rolls_Royce_Trent_800_(With_Blades)#2_001_Color_A06_0"]
                  .geometry
              }
              material={materials.Color_A06}
            />
          </group>
        </group>
        <group
          position={[167.913, 149.143, 29.779]}
          rotation={[-Math.PI / 2, 0, Math.PI]}
          scale={[0.986, 1.003, 1]}
        >
          <mesh
            geometry={nodes["Component#98_002_Color_007_0"].geometry}
            material={materials.Color_007}
            position={[-50.833, -52.918, -16.238]}
          />
        </group>
        <group
          position={[-167.913, 149.143, 29.779]}
          rotation={[-Math.PI / 2, 0, Math.PI]}
          scale={[-0.986, 1.003, 1]}
        >
          <mesh
            geometry={nodes["Component#98_001_Color_007_0"].geometry}
            material={materials.Color_007}
            position={[-50.833, -52.918, -16.238]}
          />
        </group>
        <group
          position={[-184.478, 24.141, -64.591]}
          rotation={[-Math.PI / 2, 0, Math.PI]}
          scale={[2.822, 2.797, 2.787]}
        >
          <group position={[-1.024, -5.059, -4.882]}>
            <mesh
              geometry={nodes["Group_053_<Silver>_0"].geometry}
              material={materials.Silver}
            />
            <mesh
              geometry={nodes.Group_053_skp_front_default_0.geometry}
              material={materials.skp_front_default}
            />
          </group>
        </group>
        <group
          position={[-182.789, 24.086, -64.591]}
          rotation={[-Math.PI / 2, 0, Math.PI]}
          scale={[3.767, 2.797, 2.787]}
        >
          <mesh
            geometry={nodes["Group_051_<Black>_0"].geometry}
            material={materials.Black}
            position={[-3.032, -8.957, -8.642]}
          />
        </group>
        <group
          position={[-220.704, 24.141, -64.591]}
          rotation={[-Math.PI / 2, 0, Math.PI]}
          scale={[-2.822, 2.797, 2.787]}
        >
          <group position={[-1.024, -5.059, -4.882]}>
            <mesh
              geometry={nodes["Group_050_<Silver>_0"].geometry}
              material={materials.Silver}
            />
            <mesh
              geometry={nodes.Group_050_skp_front_default_0.geometry}
              material={materials.skp_front_default}
            />
          </group>
        </group>
        <group
          position={[-222.393, 24.086, -64.591]}
          rotation={[-Math.PI / 2, 0, Math.PI]}
          scale={[-3.767, 2.797, 2.787]}
        >
          <mesh
            geometry={nodes["Group_048_<Black>_0"].geometry}
            material={materials.Black}
            position={[-3.032, -8.957, -8.642]}
          />
        </group>
        <group
          position={[-220.704, 24.141, -3.289]}
          rotation={[-Math.PI / 2, 0, Math.PI]}
          scale={[-2.822, 2.797, 2.787]}
        >
          <group position={[-1.024, -5.059, -4.882]}>
            <mesh
              geometry={nodes["Group_047_<Silver>_0"].geometry}
              material={materials.Silver}
            />
            <mesh
              geometry={nodes.Group_047_skp_front_default_0.geometry}
              material={materials.skp_front_default}
            />
          </group>
        </group>
        <group
          position={[-222.393, 24.086, -3.289]}
          rotation={[-Math.PI / 2, 0, Math.PI]}
          scale={[-3.767, 2.797, 2.787]}
        >
          <mesh
            geometry={nodes["Group_045_<Black>_0"].geometry}
            material={materials.Black}
            position={[-3.032, -8.957, -8.642]}
          />
        </group>
        <group
          position={[-184.478, 24.141, -3.289]}
          rotation={[-Math.PI / 2, 0, Math.PI]}
          scale={[2.822, 2.797, 2.787]}
        >
          <group position={[-1.024, -5.059, -4.882]}>
            <mesh
              geometry={nodes["Group_044_<Silver>_0"].geometry}
              material={materials.Silver}
            />
            <mesh
              geometry={nodes.Group_044_skp_front_default_0.geometry}
              material={materials.skp_front_default}
            />
          </group>
        </group>
        <group
          position={[-182.789, 24.086, -3.289]}
          rotation={[-Math.PI / 2, 0, Math.PI]}
          scale={[3.767, 2.797, 2.787]}
        >
          <mesh
            geometry={nodes["Group_042_<Black>_0"].geometry}
            material={materials.Black}
            position={[-3.032, -8.957, -8.642]}
          />
        </group>
        <group
          position={[-220.704, 24.141, 58.014]}
          rotation={[-Math.PI / 2, 0, Math.PI]}
          scale={[-2.822, 2.797, 2.787]}
        >
          <group position={[-1.024, -5.059, -4.882]}>
            <mesh
              geometry={nodes["Group_041_<Silver>_0"].geometry}
              material={materials.Silver}
            />
            <mesh
              geometry={nodes.Group_041_skp_front_default_0.geometry}
              material={materials.skp_front_default}
            />
          </group>
        </group>
        <group
          position={[-222.393, 24.086, 58.014]}
          rotation={[-Math.PI / 2, 0, Math.PI]}
          scale={[-3.767, 2.797, 2.787]}
        >
          <mesh
            geometry={nodes["Group_039_<Black>_0"].geometry}
            material={materials.Black}
            position={[-3.032, -8.957, -8.642]}
          />
        </group>
        <group
          position={[-184.478, 24.141, 58.014]}
          rotation={[-Math.PI / 2, 0, Math.PI]}
          scale={[2.822, 2.797, 2.787]}
        >
          <group position={[-1.024, -5.059, -4.882]}>
            <mesh
              geometry={nodes["Group_038_<Silver>_0"].geometry}
              material={materials.Silver}
            />
            <mesh
              geometry={nodes.Group_038_skp_front_default_0.geometry}
              material={materials.skp_front_default}
            />
          </group>
        </group>
        <group
          position={[-182.789, 24.086, 58.014]}
          rotation={[-Math.PI / 2, 0, Math.PI]}
          scale={[3.767, 2.797, 2.787]}
        >
          <mesh
            geometry={nodes["Group_036_<Black>_0"].geometry}
            material={materials.Black}
            position={[-3.032, -8.957, -8.642]}
          />
        </group>
        <group
          position={[-202.591, 24.141, -3.233]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[-1.322, 1.346, 1.341]}
        >
          <group position={[-15.202, -47.857, -2.659]}>
            <mesh
              geometry={nodes["Group_035_<Silver>_0"].geometry}
              material={materials.Silver}
            />
            <mesh
              geometry={nodes["Group_035_<Gainsboro>1_0"].geometry}
              material={materials.Gainsboro1}
            />
          </group>
        </group>
        <group
          position={[-155.119, 93.476, 5.781]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[-1.322, 1.346, 1.341]}
        >
          <mesh
            geometry={nodes["Group_033_<Silver>_0"].geometry}
            material={materials.Silver}
            position={[-52.926, -57.429, -69.7]}
          />
        </group>
        <group
          position={[206.052, 283.683, -1241.884]}
          rotation={[-Math.PI / 2, 0, Math.PI]}
          scale={[0.707, 0.72, 0.718]}
        >
          <mesh
            geometry={nodes["Component#71_002_777_texture_0"].geometry}
            material={materials["777_texture"]}
            position={[-300.461, -295.599, -50.697]}
          />
        </group>
        <group
          position={[-206.052, 283.683, -1241.884]}
          rotation={[-Math.PI / 2, 0, Math.PI]}
          scale={[-0.707, 0.72, 0.718]}
        >
          <mesh
            geometry={nodes["Component#71_001_777_texture_0"].geometry}
            material={materials["777_texture"]}
            position={[-300.461, -295.598, -50.697]}
          />
        </group>
        <group
          position={[0, 290.582, -1344.859]}
          rotation={[-Math.PI / 2, 0, Math.PI]}
          scale={[-0.986, 1.003, 1]}
        >
          <group position={[-424.704, -109.503, -43.287]}>
            <mesh
              geometry={nodes.Group_032_skp_front_default_0.geometry}
              material={materials.skp_front_default}
            />
            <mesh
              geometry={nodes.Group_032_777_texture_0.geometry}
              material={materials["777_texture"]}
            />
          </group>
        </group>
        <group
          position={[-714.732, 250.297, -189.965]}
          rotation={[1.377, -0.184, -2.776]}
          scale={[-0.707, 0.72, 0.718]}
        >
          <mesh
            geometry={
              nodes["Component#67_002_20080711_gallery-777-300ER-top_0"]
                .geometry
            }
            material={materials["20080711_gallery-777-300ER-top"]}
            position={[-57.838, -22.733, -2.623]}
          />
        </group>
        <group
          position={[-640.995, 242.301, -159.126]}
          rotation={[1.374, -0.185, -2.777]}
          scale={[-0.707, 0.72, 0.718]}
        >
          <mesh
            geometry={
              nodes["Component#66_002_20080711_gallery-777-300ER-top_0"]
                .geometry
            }
            material={materials["20080711_gallery-777-300ER-top"]}
            position={[-57.698, -22.692, -2.667]}
          />
        </group>
        <group
          position={[-568.226, 234.447, -128.667]}
          rotation={[1.374, -0.185, -2.777]}
          scale={[-0.707, 0.72, 0.718]}
        >
          <mesh
            geometry={
              nodes["Component#65_002_20080711_gallery-777-300ER-top_0"]
                .geometry
            }
            material={materials["20080711_gallery-777-300ER-top"]}
            position={[-56.524, -22.598, -2.743]}
          />
        </group>
        <group
          position={[-496.156, 226.735, -98.442]}
          rotation={[1.374, -0.185, -2.777]}
          scale={[-0.707, 0.72, 0.718]}
        >
          <mesh
            geometry={
              nodes["Component#64_002_20080711_gallery-777-300ER-top_0"]
                .geometry
            }
            material={materials["20080711_gallery-777-300ER-top"]}
            position={[-56.402, -22.41, -2.743]}
          />
        </group>
        <group
          position={[-288.728, 200.163, -52.452]}
          rotation={[1.375, -0.147, 3.121]}
          scale={[-0.707, 0.72, 0.718]}
        >
          <mesh
            geometry={
              nodes["Component#63_003_20080711_gallery-777-300ER-top_0"]
                .geometry
            }
            material={materials["20080711_gallery-777-300ER-top"]}
            position={[-54.501, -30.998, -3.951]}
          />
        </group>
        <group
          position={[-205.784, 186.602, -52.192]}
          rotation={[-1.788, 0.172, 0.047]}
          scale={[-0.707, 0.72, 0.718]}
        >
          <mesh
            geometry={
              nodes["Component#62_002_20080711_gallery-777-300ER-top_0"]
                .geometry
            }
            material={materials["20080711_gallery-777-300ER-top"]}
            position={[-59.8, -30.537, 3.176]}
          />
        </group>
        <group
          position={[-1091.01, 290.298, -288.909]}
          rotation={[-1.509, 0.088, 2.529]}
          scale={[-0.707, 0.72, 0.718]}
        >
          <mesh
            geometry={
              nodes["Component#59_002_20080711_gallery-777-300ER-top_0"]
                .geometry
            }
            material={materials["20080711_gallery-777-300ER-top"]}
            position={[-97.598, -18.363, -9.341]}
          />
        </group>
        <group
          position={[-974.851, 276.43, -207.187]}
          rotation={[-1.509, 0.088, 2.529]}
          scale={[-0.707, 0.72, 0.718]}
        >
          <mesh
            geometry={
              nodes["Component#58_001_20080711_gallery-777-300ER-top_0"]
                .geometry
            }
            material={materials["20080711_gallery-777-300ER-top"]}
            position={[-101.353, -18.988, -11.326]}
          />
        </group>
        <group
          position={[-852.221, 261.436, -121.292]}
          rotation={[-1.509, 0.088, 2.529]}
          scale={[-0.707, 0.72, 0.718]}
        >
          <mesh
            geometry={
              nodes["Component#57_001_20080711_gallery-777-300ER-top_0"]
                .geometry
            }
            material={materials["20080711_gallery-777-300ER-top"]}
            position={[-108.115, -19.213, -12.9]}
          />
        </group>
        <group
          position={[-726.004, 245.966, -33.232]}
          rotation={[-1.506, 0.092, 2.529]}
          scale={[-0.707, 0.72, 0.718]}
        >
          <mesh
            geometry={
              nodes["Component#56_002_20080711_gallery-777-300ER-top_0"]
                .geometry
            }
            material={materials["20080711_gallery-777-300ER-top"]}
            position={[-106.772, -19.046, -15.832]}
          />
        </group>
        <group
          position={[-598.619, 230.075, 55.571]}
          rotation={[-1.509, 0.088, 2.529]}
          scale={[-0.707, 0.72, 0.718]}
        >
          <group position={[-109.603, -18.797, -16.883]}>
            <mesh
              geometry={
                nodes["Component#55_002_20080711_gallery-777-300ER-top_0"]
                  .geometry
              }
              material={materials["20080711_gallery-777-300ER-top"]}
            />
            <mesh
              geometry={nodes["Component#55_002_skp_front_default_0"].geometry}
              material={materials.skp_front_default}
            />
          </group>
        </group>
        <group
          position={[-457.887, 212.406, 153.696]}
          rotation={[-1.509, 0.088, 2.529]}
          scale={[-0.707, 0.72, 0.718]}
        >
          <mesh
            geometry={
              nodes["Component#53_002_20080711_gallery-777-300ER-top_0"]
                .geometry
            }
            material={materials["20080711_gallery-777-300ER-top"]}
            position={[-129.473, -18.541, -18.094]}
          />
        </group>
        <group
          position={[-230.96, 180.787, 310.692]}
          rotation={[-1.47, 0.157, 2.568]}
          scale={[-0.707, 0.72, 0.718]}
        >
          <mesh
            geometry={
              nodes["Component#52_002_20080711_gallery-777-300ER-top_0"]
                .geometry
            }
            material={materials["20080711_gallery-777-300ER-top"]}
            position={[-150.718, -23.879, -29.948]}
          />
        </group>
        <group
          position={[-1025.531, 284.332, -342.854]}
          rotation={[-1.479, 0.084, -0.442]}
          scale={[-0.707, 0.72, 0.718]}
        >
          <mesh
            geometry={
              nodes["Component#50_002_20080711_gallery-777-300ER-top_0"]
                .geometry
            }
            material={materials["20080711_gallery-777-300ER-top"]}
            position={[-187.089, -21.156, -7.054]}
          />
        </group>
        <group
          position={[-654.035, 240.526, -196.315]}
          rotation={[-1.476, 0.092, -0.421]}
          scale={[-0.707, 0.72, 0.718]}
        >
          <mesh
            geometry={
              nodes["Component#49_002_20080711_gallery-777-300ER-top_0"]
                .geometry
            }
            material={materials["20080711_gallery-777-300ER-top"]}
            position={[-380.372, -47.429, -11.746]}
          />
        </group>
        <group
          position={[-370.852, 204.036, -102.052]}
          rotation={[-1.458, 0.124, -0.088]}
          scale={[-0.707, 0.72, 0.718]}
        >
          <group position={[-64.859, -32.329, -12.212]}>
            <mesh
              geometry={nodes["Component#48_002_777_texture_0"].geometry}
              material={materials["777_texture"]}
            />
            <mesh
              geometry={
                nodes["Component#48_002_20080711_gallery-777-300ER-top_0"]
                  .geometry
              }
              material={materials["20080711_gallery-777-300ER-top"]}
            />
            <mesh
              geometry={nodes["Component#48_002_skp_front_default_0"].geometry}
              material={materials.skp_front_default}
            />
          </group>
        </group>
        <group
          position={[-222.88, 177.458, -80.011]}
          rotation={[-1.44, 0.199, -0.054]}
          scale={[-0.707, 0.72, 0.718]}
        >
          <mesh
            geometry={
              nodes["Component#47_002_20080711_gallery-777-300ER-top_0"]
                .geometry
            }
            material={materials["20080711_gallery-777-300ER-top"]}
            position={[-152.723, -54.898, -13.36]}
          />
        </group>
        <group
          position={[-678.859, 217.444, -26.639]}
          rotation={[-Math.PI / 2, 0, Math.PI]}
          scale={[-0.986, 1.003, 1]}
        >
          <mesh
            geometry={
              nodes["Component#81_001_20080711_gallery-777-300ER-top_0"]
                .geometry
            }
            material={materials["20080711_gallery-777-300ER-top"]}
            position={[-497.421, -386.485, -101.022]}
          />
        </group>
        <group
          position={[788.264, 258.268, -220.721]}
          rotation={[1.382, 0.182, 2.775]}
          scale={[0.707, 0.72, 0.718]}
        >
          <group position={[-55.153, -22.773, -2.627]}>
            <mesh
              geometry={
                nodes["Component#68_003_20080711_gallery-777-300ER-top_0"]
                  .geometry
              }
              material={materials["20080711_gallery-777-300ER-top"]}
            />
            <mesh
              geometry={nodes["Component#68_003_skp_front_default_0"].geometry}
              material={materials.skp_front_default}
            />
          </group>
        </group>
        <group
          position={[714.732, 250.297, -189.965]}
          rotation={[1.377, 0.184, 2.776]}
          scale={[0.707, 0.72, 0.718]}
        >
          <mesh
            geometry={
              nodes["Component#67_001_20080711_gallery-777-300ER-top_0"]
                .geometry
            }
            material={materials["20080711_gallery-777-300ER-top"]}
            position={[-57.838, -22.733, -2.624]}
          />
        </group>
        <group
          position={[640.994, 242.301, -159.126]}
          rotation={[1.374, 0.185, 2.777]}
          scale={[0.707, 0.72, 0.718]}
        >
          <mesh
            geometry={
              nodes["Component#66_001_20080711_gallery-777-300ER-top_0"]
                .geometry
            }
            material={materials["20080711_gallery-777-300ER-top"]}
            position={[-57.698, -22.692, -2.667]}
          />
        </group>
        <group
          position={[568.226, 234.447, -128.667]}
          rotation={[1.374, 0.185, 2.777]}
          scale={[0.707, 0.72, 0.718]}
        >
          <mesh
            geometry={
              nodes["Component#65_001_20080711_gallery-777-300ER-top_0"]
                .geometry
            }
            material={materials["20080711_gallery-777-300ER-top"]}
            position={[-56.524, -22.598, -2.743]}
          />
        </group>
        <group
          position={[496.155, 226.735, -98.442]}
          rotation={[1.374, 0.185, 2.777]}
          scale={[0.707, 0.72, 0.718]}
        >
          <mesh
            geometry={
              nodes["Component#64_001_20080711_gallery-777-300ER-top_0"]
                .geometry
            }
            material={materials["20080711_gallery-777-300ER-top"]}
            position={[-56.402, -22.41, -2.743]}
          />
        </group>
        <group
          position={[288.728, 200.163, -52.452]}
          rotation={[1.375, 0.147, -3.121]}
          scale={[0.707, 0.72, 0.718]}
        >
          <mesh
            geometry={
              nodes["Component#63_001_20080711_gallery-777-300ER-top_0"]
                .geometry
            }
            material={materials["20080711_gallery-777-300ER-top"]}
            position={[-54.501, -30.998, -3.951]}
          />
        </group>
        <group
          position={[205.784, 186.602, -52.192]}
          rotation={[-1.788, -0.172, -0.047]}
          scale={[0.707, 0.72, 0.718]}
        >
          <mesh
            geometry={
              nodes["Component#62_001_20080711_gallery-777-300ER-top_0"]
                .geometry
            }
            material={materials["20080711_gallery-777-300ER-top"]}
            position={[-59.8, -30.537, 3.176]}
          />
        </group>
        <group
          position={[1091.01, 290.298, -288.909]}
          rotation={[-1.509, -0.088, -2.529]}
          scale={[0.707, 0.72, 0.718]}
        >
          <mesh
            geometry={
              nodes["Component#59_001_20080711_gallery-777-300ER-top_0"]
                .geometry
            }
            material={materials["20080711_gallery-777-300ER-top"]}
            position={[-97.598, -18.363, -9.341]}
          />
        </group>
        <group
          position={[726.004, 245.966, -33.232]}
          rotation={[-1.506, -0.092, -2.529]}
          scale={[0.707, 0.72, 0.718]}
        >
          <mesh
            geometry={
              nodes["Component#56_001_20080711_gallery-777-300ER-top_0"]
                .geometry
            }
            material={materials["20080711_gallery-777-300ER-top"]}
            position={[-106.772, -19.046, -15.832]}
          />
        </group>
        <group
          position={[598.619, 230.075, 55.571]}
          rotation={[-1.509, -0.088, -2.529]}
          scale={[0.707, 0.72, 0.718]}
        >
          <group position={[-109.603, -18.797, -16.883]}>
            <mesh
              geometry={
                nodes["Component#55_001_20080711_gallery-777-300ER-top_0"]
                  .geometry
              }
              material={materials["20080711_gallery-777-300ER-top"]}
            />
            <mesh
              geometry={nodes["Component#55_001_skp_front_default_0"].geometry}
              material={materials.skp_front_default}
            />
          </group>
        </group>
        <group
          position={[457.887, 212.406, 153.696]}
          rotation={[-1.509, -0.088, -2.529]}
          scale={[0.707, 0.72, 0.718]}
        >
          <mesh
            geometry={
              nodes["Component#53_001_20080711_gallery-777-300ER-top_0"]
                .geometry
            }
            material={materials["20080711_gallery-777-300ER-top"]}
            position={[-129.473, -18.541, -18.094]}
          />
        </group>
        <group
          position={[230.96, 180.787, 310.692]}
          rotation={[-1.47, -0.157, -2.568]}
          scale={[0.707, 0.72, 0.718]}
        >
          <mesh
            geometry={
              nodes["Component#52_001_20080711_gallery-777-300ER-top_0"]
                .geometry
            }
            material={materials["20080711_gallery-777-300ER-top"]}
            position={[-150.718, -23.879, -29.948]}
          />
        </group>
        <group
          position={[1025.531, 284.332, -342.854]}
          rotation={[-1.479, -0.084, 0.442]}
          scale={[0.707, 0.72, 0.718]}
        >
          <mesh
            geometry={
              nodes["Component#50_001_20080711_gallery-777-300ER-top_0"]
                .geometry
            }
            material={materials["20080711_gallery-777-300ER-top"]}
            position={[-187.089, -21.156, -7.053]}
          />
        </group>
        <group
          position={[654.035, 240.526, -196.315]}
          rotation={[-1.476, -0.092, 0.421]}
          scale={[0.707, 0.72, 0.718]}
        >
          <mesh
            geometry={
              nodes["Component#49_001_20080711_gallery-777-300ER-top_0"]
                .geometry
            }
            material={materials["20080711_gallery-777-300ER-top"]}
            position={[-380.372, -47.429, -11.746]}
          />
        </group>
        <group
          position={[370.852, 204.036, -102.052]}
          rotation={[-1.458, -0.124, 0.088]}
          scale={[0.707, 0.72, 0.718]}
        >
          <group position={[-64.859, -32.329, -12.212]}>
            <mesh
              geometry={nodes["Component#48_001_777_texture_0"].geometry}
              material={materials["777_texture"]}
            />
            <mesh
              geometry={
                nodes["Component#48_001_20080711_gallery-777-300ER-top_0"]
                  .geometry
              }
              material={materials["20080711_gallery-777-300ER-top"]}
            />
            <mesh
              geometry={nodes["Component#48_001_skp_front_default_0"].geometry}
              material={materials.skp_front_default}
            />
          </group>
        </group>
        <group
          position={[222.88, 177.458, -80.011]}
          rotation={[-1.44, -0.199, 0.054]}
          scale={[0.707, 0.72, 0.718]}
        >
          <mesh
            geometry={
              nodes["Component#47_001_20080711_gallery-777-300ER-top_0"]
                .geometry
            }
            material={materials["20080711_gallery-777-300ER-top"]}
            position={[-152.723, -54.898, -13.36]}
          />
        </group>
        <group
          position={[-788.265, 258.268, -220.721]}
          rotation={[1.382, -0.182, -2.775]}
          scale={[-0.707, 0.72, 0.718]}
        >
          <group position={[-55.153, -22.773, -2.627]}>
            <mesh
              geometry={
                nodes["Component#68_001_20080711_gallery-777-300ER-top_0"]
                  .geometry
              }
              material={materials["20080711_gallery-777-300ER-top"]}
            />
            <mesh
              geometry={nodes["Component#68_001_skp_front_default_0"].geometry}
              material={materials.skp_front_default}
            />
          </group>
        </group>
        <group
          position={[0, 198.076, -98.283]}
          rotation={[-Math.PI / 2, 0, Math.PI]}
          scale={[-0.986, 1.003, 1]}
        >
          <mesh
            geometry={nodes.Group_031_Color_0032_0.geometry}
            material={materials.Color_0032}
            position={[-767.864, -169.352, -47.467]}
          />
        </group>
        <group
          position={[678.859, 217.444, -26.639]}
          rotation={[-Math.PI / 2, 0, Math.PI]}
          scale={[-0.986, 1.003, 1]}
        >
          <group position={[-1874.924, -1230.991, -217.512]}>
            <mesh
              geometry={
                nodes["Group_029_20080711_gallery-777-300ER-top_0"].geometry
              }
              material={materials["20080711_gallery-777-300ER-top"]}
            />
            <mesh
              geometry={nodes.Group_029_Color_009_0.geometry}
              material={materials.Color_009}
            />
          </group>
        </group>
        <group
          position={[18.135, 22.754, 1224.016]}
          rotation={[-Math.PI / 2, 0, Math.PI]}
          scale={[2.647, 2.623, 2.614]}
        >
          <group position={[-1.024, -5.059, -4.882]}>
            <mesh
              geometry={nodes["Group_028_<Silver>_0"].geometry}
              material={materials.Silver}
            />
            <mesh
              geometry={nodes.Group_028_skp_front_default_0.geometry}
              material={materials.skp_front_default}
            />
          </group>
        </group>
        <group
          position={[16.934, 22.702, 1224.016]}
          rotation={[-Math.PI / 2, 0, Math.PI]}
          scale={[3.533, 2.623, 2.614]}
        >
          <mesh
            geometry={nodes["Group_027_<Black>_0"].geometry}
            material={materials.Black}
            position={[-3.82, -8.957, -8.642]}
          />
        </group>
        <group
          position={[-17.949, 22.754, 1224.016]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[2.647, 2.623, 2.614]}
        >
          <group position={[-1.024, -5.059, -4.882]}>
            <mesh
              geometry={nodes["Group_026_<Silver>_0"].geometry}
              material={materials.Silver}
            />
            <mesh
              geometry={nodes.Group_026_skp_front_default_0.geometry}
              material={materials.skp_front_default}
            />
          </group>
        </group>
        <group
          position={[-16.749, 22.702, 1224.016]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[3.533, 2.623, 2.614]}
        >
          <mesh
            geometry={nodes["Group_025_<Black>_0"].geometry}
            material={materials.Black}
            position={[-3.82, -8.957, -8.642]}
          />
        </group>
        <group
          position={[-0.09, 83.866, 1238.858]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[-2.022, 2.058, 2.051]}
        >
          <group position={[-15.647, -22.772, -40.847]}>
            <mesh
              geometry={nodes.Group_024_skp_front_default_0.geometry}
              material={materials.skp_front_default}
            />
            <mesh
              geometry={nodes["Group_024_<Gainsboro>1_0"].geometry}
              material={materials.Gainsboro1}
            />
          </group>
        </group>
        <group
          position={[0, 107.7, 25.307]}
          rotation={[-Math.PI / 2, 0, Math.PI]}
          scale={[-0.986, 1.003, 1]}
        >
          <mesh
            geometry={
              nodes["Group_023_20080711_gallery-777-300ER-top_0"].geometry
            }
            material={materials["20080711_gallery-777-300ER-top"]}
            position={[-242.566, -55.057, -52.014]}
          />
        </group>
        <group
          position={[0, 107.757, 1254.236]}
          rotation={[-Math.PI / 2, 0, Math.PI]}
          scale={[-0.986, 1.003, 1.13]}
        >
          <group position={[-31.52, -36.554, -15.913]}>
            <mesh
              geometry={nodes.Group_022_Color_0041_0.geometry}
              material={materials.Color_0041}
            />
            <mesh
              geometry={nodes.Group_022_Color_000_0.geometry}
              material={materials.Color_000}
            />
            <mesh
              geometry={nodes.Group_022_Color_A11_0.geometry}
              material={materials.Color_A11}
            />
          </group>
        </group>
        <group
          position={[184.478, 24.141, -64.591]}
          rotation={[-Math.PI / 2, 0, Math.PI]}
          scale={[-2.822, 2.797, 2.787]}
        >
          <group position={[-1.024, -5.059, -4.882]}>
            <mesh
              geometry={nodes["Group_021_<Silver>_0"].geometry}
              material={materials.Silver}
            />
            <mesh
              geometry={nodes.Group_021_skp_front_default_0.geometry}
              material={materials.skp_front_default}
            />
          </group>
        </group>
        <group
          position={[182.789, 24.086, -64.591]}
          rotation={[-Math.PI / 2, 0, Math.PI]}
          scale={[-3.767, 2.797, 2.787]}
        >
          <mesh
            geometry={nodes["Group_019_<Black>_0"].geometry}
            material={materials.Black}
            position={[-3.031, -8.957, -8.642]}
          />
        </group>
        <group
          position={[220.704, 24.141, -64.591]}
          rotation={[-Math.PI / 2, 0, Math.PI]}
          scale={[2.822, 2.797, 2.787]}
        >
          <group position={[-1.024, -5.059, -4.882]}>
            <mesh
              geometry={nodes["Group_018_<Silver>_0"].geometry}
              material={materials.Silver}
            />
            <mesh
              geometry={nodes.Group_018_skp_front_default_0.geometry}
              material={materials.skp_front_default}
            />
          </group>
        </group>
        <group
          position={[222.393, 24.086, -64.591]}
          rotation={[-Math.PI / 2, 0, Math.PI]}
          scale={[3.767, 2.797, 2.787]}
        >
          <mesh
            geometry={nodes["Group_016_<Black>_0"].geometry}
            material={materials.Black}
            position={[-3.031, -8.957, -8.642]}
          />
        </group>
        <group
          position={[220.704, 24.141, -3.289]}
          rotation={[-Math.PI / 2, 0, Math.PI]}
          scale={[2.822, 2.797, 2.787]}
        >
          <group position={[-1.024, -5.059, -4.882]}>
            <mesh
              geometry={nodes["Group_015_<Silver>_0"].geometry}
              material={materials.Silver}
            />
            <mesh
              geometry={nodes.Group_015_skp_front_default_0.geometry}
              material={materials.skp_front_default}
            />
          </group>
        </group>
        <group
          position={[222.393, 24.086, -3.289]}
          rotation={[-Math.PI / 2, 0, Math.PI]}
          scale={[3.767, 2.797, 2.787]}
        >
          <mesh
            geometry={nodes["Group_013_<Black>_0"].geometry}
            material={materials.Black}
            position={[-3.031, -8.957, -8.642]}
          />
        </group>
        <group
          position={[184.478, 24.141, -3.289]}
          rotation={[-Math.PI / 2, 0, Math.PI]}
          scale={[-2.822, 2.797, 2.787]}
        >
          <group position={[-1.024, -5.059, -4.882]}>
            <mesh
              geometry={nodes["Group_012_<Silver>_0"].geometry}
              material={materials.Silver}
            />
            <mesh
              geometry={nodes.Group_012_skp_front_default_0.geometry}
              material={materials.skp_front_default}
            />
          </group>
        </group>
        <group
          position={[182.789, 24.086, -3.289]}
          rotation={[-Math.PI / 2, 0, Math.PI]}
          scale={[-3.767, 2.797, 2.787]}
        >
          <mesh
            geometry={nodes["Group_010_<Black>_0"].geometry}
            material={materials.Black}
            position={[-3.031, -8.957, -8.642]}
          />
        </group>
        <group
          position={[220.704, 24.141, 58.014]}
          rotation={[-Math.PI / 2, 0, Math.PI]}
          scale={[2.822, 2.797, 2.787]}
        >
          <group position={[-1.024, -5.059, -4.882]}>
            <mesh
              geometry={nodes["Group_009_<Silver>_0"].geometry}
              material={materials.Silver}
            />
            <mesh
              geometry={nodes.Group_009_skp_front_default_0.geometry}
              material={materials.skp_front_default}
            />
          </group>
        </group>
        <group
          position={[222.393, 24.086, 58.014]}
          rotation={[-Math.PI / 2, 0, Math.PI]}
          scale={[3.767, 2.797, 2.787]}
        >
          <mesh
            geometry={nodes["Group_007_<Black>_0"].geometry}
            material={materials.Black}
            position={[-3.031, -8.957, -8.642]}
          />
        </group>
        <group
          position={[184.478, 24.141, 58.014]}
          rotation={[-Math.PI / 2, 0, Math.PI]}
          scale={[-2.822, 2.797, 2.787]}
        >
          <group position={[-1.024, -5.059, -4.882]}>
            <mesh
              geometry={nodes["Group_006_<Silver>_0"].geometry}
              material={materials.Silver}
            />
            <mesh
              geometry={nodes.Group_006_skp_front_default_0.geometry}
              material={materials.skp_front_default}
            />
          </group>
        </group>
        <group
          position={[182.789, 24.086, 58.014]}
          rotation={[-Math.PI / 2, 0, Math.PI]}
          scale={[-3.767, 2.797, 2.787]}
        >
          <mesh
            geometry={nodes["Group_004_<Black>_0"].geometry}
            material={materials.Black}
            position={[-3.031, -8.957, -8.642]}
          />
        </group>
        <group
          position={[202.591, 24.141, -3.233]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[1.322, 1.346, 1.341]}
        >
          <group position={[-15.202, -47.857, -2.659]}>
            <mesh
              geometry={nodes["Group_003_<Silver>_0"].geometry}
              material={materials.Silver}
            />
            <mesh
              geometry={nodes["Group_003_<Gainsboro>1_0"].geometry}
              material={materials.Gainsboro1}
            />
          </group>
        </group>
        <group
          position={[155.118, 93.476, 5.781]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[1.322, 1.346, 1.341]}
        >
          <mesh
            geometry={nodes["Group_001_<Silver>_0"].geometry}
            material={materials.Silver}
            position={[-52.926, -57.429, -69.7]}
          />
        </group>
        <group position={[0, 227.853, 17.431]} rotation={[-Math.PI / 2, 0, 0]}>
          <mesh
            geometry={nodes.Layer0_001_Color_0001_0.geometry}
            material={materials.Color_0001}
          />
          <mesh
            geometry={nodes.Layer0_001_Color_0041_0.geometry}
            material={materials.Color_0041}
          />
          <mesh
            geometry={nodes.Layer0_001_Color_000_0.geometry}
            material={materials.Color_000}
          />
          <mesh
            geometry={nodes.Layer0_001_Color_I16_0.geometry}
            material={materials.Color_I16}
          />
          <mesh
            geometry={nodes.Layer0_001_Color_A06_0.geometry}
            material={materials.Color_A06}
          />
          <mesh
            geometry={nodes.Layer0_001_Color_003_0.geometry}
            material={materials.Color_003}
          />
          <mesh
            geometry={nodes.Layer0_001_Color_I12_0.geometry}
            material={materials.Color_I12}
          />
          <mesh
            geometry={nodes.Layer0_001_Translucent_Glass_Gray1_0.geometry}
            material={materials.Translucent_Glass_Gray1}
          />
          <mesh
            geometry={nodes.Layer0_001_Color_007_0.geometry}
            material={materials.Color_007}
          />
          <mesh
            geometry={nodes.Layer0_001_777_vertical_stabilizer3_0.geometry}
            material={materials["777_vertical_stabilizer3"]}
          />
          <mesh
            geometry={nodes.Layer0_001_Material14_0.geometry}
            material={materials.Material14}
          />
          <mesh
            geometry={nodes["Layer0_001_<Silver>1_0"].geometry}
            material={materials.Silver1}
          />
          <mesh
            geometry={nodes.Layer0_001_Material13_0.geometry}
            material={materials.Material13}
          />
          <mesh
            geometry={nodes.Layer0_001_skp_front_default_0.geometry}
            material={materials.skp_front_default}
          />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload("/plane.gltf")
